begin;
do $$
declare o1 uuid:=gen_random_uuid(); o2 uuid:=gen_random_uuid(); m1 uuid:=gen_random_uuid(); m2 uuid:=gen_random_uuid(); learner uuid:=gen_random_uuid(); c uuid; v uuid; p uuid; a uuid; r jsonb; content jsonb; lesson uuid:=gen_random_uuid(); quiz uuid:=gen_random_uuid(); practice uuid:=gen_random_uuid(); req uuid:=gen_random_uuid(); connection uuid; pr uuid;
begin
 insert into organisations(id,name) values(o1,'LMS rollback test provider'),(o2,'LMS rollback test employer');
 insert into auth.users(id,email) values(m1,m1||'@example.invalid'),(m2,m2||'@example.invalid'),(learner,learner||'@example.invalid');
 insert into user_profiles(id,org_id,role,email,name) values(m1,o1,'admin',m1||'@example.invalid','Provider'),(m2,o2,'admin',m2||'@example.invalid','Employer'),(learner,o2,'user',learner||'@example.invalid','Learner') on conflict(id) do update set org_id=excluded.org_id,role=excluded.role;
 content:=jsonb_build_object('title','Learning test','summary','Test only','category','ai','outcomes',jsonb_build_array('Evaluate outputs'),'activities',jsonb_build_array(jsonb_build_object('id',lesson,'kind','lesson','title','Learn','content','Read this','minutes',5),jsonb_build_object('id',quiz,'kind','quiz','title','Check','content','Choose','minutes',5,'options',jsonb_build_array('Wrong','Right'),'correctOption',1),jsonb_build_object('id',practice,'kind','practice','title','Try','content','Explain your checks','minutes',5,'criteria','Describe two checks')));
 r:=lms_command(m1,'course.save',jsonb_build_object('content',content),req); c:=(r->>'id')::uuid;
 assert lms_command(m1,'course.save',jsonb_build_object('content',content),req)=r,'Idempotency failed';
 begin perform lms_command(learner,'course.save',jsonb_build_object('content',content)); raise exception 'Learner managed course'; exception when insufficient_privilege then null; end;
 begin perform lms_command(m2,'course.get',jsonb_build_object('id',c)); raise exception 'Cross tenant read'; exception when no_data_found then null; end;
 r:=lms_command(m1,'course.publish',jsonb_build_object('id',c,'revision',1)); v:=(r->>'id')::uuid;
 begin perform lms_command(m1,'programme.create',jsonb_build_object('title','Test','goal','Goal','version_ids',jsonb_build_array(v),'client_org_id',o2)); raise exception 'Unaccepted client access'; exception when insufficient_privilege then null; end;
 r:=lms_command(m1,'client.request',jsonb_build_object('client_org_id',o2)); connection:=(r->>'id')::uuid;
 perform lms_command(m2,'client.respond',jsonb_build_object('id',connection,'accept',true));
 r:=lms_command(m1,'programme.create',jsonb_build_object('title','Test','goal','Goal','version_ids',jsonb_build_array(v),'client_org_id',o2)); p:=(r->>'id')::uuid;
 perform lms_command(m2,'programme.assign',jsonb_build_object('id',p,'user_ids',jsonb_build_array(learner)));
 select id into a from lms_assignments where programme_id=p and user_id=learner;
 r:=lms_command(learner,'learning.get',jsonb_build_object('id',a));
 assert r::text not like '%correctOption%','Answer key leaked';
 perform lms_command(learner,'learning.submit',jsonb_build_object('id',a,'activity_id',lesson));
 perform lms_command(learner,'learning.submit',jsonb_build_object('id',a,'activity_id',quiz,'option',0));
 assert not exists(select 1 from lms_assignments where id=a and completed_at is not null),'Wrong answer completed';
 perform lms_command(learner,'learning.submit',jsonb_build_object('id',a,'activity_id',quiz,'option',1));
 r:=lms_command(learner,'learning.submit',jsonb_build_object('id',a,'activity_id',practice,'answer','I check the source and compare a second source.')); pr:=(r->>'id')::uuid;
 assert not exists(select 1 from lms_assignments where id=a and completed_at is not null),'Unreviewed practice completed';
 perform lms_command(m1,'learning.review',jsonb_build_object('id',pr,'revision',1,'decision','passed','feedback','Meets both checks.'));
 assert exists(select 1 from lms_assignments where id=a and completed_at is not null),'Completion missing';
 assert (select count(*) from lms_attempt_history where assignment_id=a)=5,'Attempt history missing';
 begin perform lms_command(m1,'learning.review',jsonb_build_object('id',pr,'revision',1,'decision','returned','feedback','Stale review')); raise exception 'Stale review accepted'; exception when serialization_failure then null; end;
 perform lms_command(m1,'course.save',jsonb_build_object('id',c,'revision',1,'content',content||'{"title":"Changed draft"}'));
 assert (select cv.content->>'title' from lms_course_versions cv where cv.id=v)='Learning test','Published version changed';
 assert not has_function_privilege('authenticated','lms_command(uuid,text,jsonb,uuid)','EXECUTE'),'Browser can impersonate actor';
 assert not has_table_privilege('authenticated','lms_course_versions','SELECT'),'Browser can read answer keys';
 r:=lms_command(m2,'record.get',jsonb_build_object('id',a));
 assert jsonb_array_length(r->'history')=5,'Employer evidence access missing';
 begin perform lms_command(learner,'record.get',jsonb_build_object('id',a)); raise exception 'Learner can access manager records'; exception when insufficient_privilege then null; end;
 perform lms_command(m2,'client.disconnect',jsonb_build_object('id',connection));
 r:=lms_command(m1,'overview','{}');
 assert not exists(select 1 from jsonb_array_elements(r->'members') m where m->>'id'=learner::text),'Disconnected provider still sees roster';
 begin perform lms_command(m1,'programme.assign',jsonb_build_object('id',p,'user_ids',jsonb_build_array(learner))); raise exception 'Disconnected assignment accepted'; exception when insufficient_privilege then null; end;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',learner,'role','authenticated')::text,true);
 execute 'set local role authenticated';
 update user_profiles set name='Descriptive profile edit allowed' where id=learner;
 begin update user_profiles set role='super_admin' where id=learner; raise exception 'Self-promotion allowed'; exception when insufficient_privilege then null; end;
 begin update user_profiles set org_id=o1 where id=learner; raise exception 'Self tenant change allowed'; exception when insufficient_privilege then null; end;
 begin update user_profiles set email='ag@experrt.com' where id=learner; raise exception 'Email promotion allowed'; exception when insufficient_privilege then null; end;
 execute 'reset role';
 perform lms_command(m1,'overview','{}'); perform lms_command(m2,'programme.get',jsonb_build_object('id',p));
 r:=lms_command(m1,'agent.create',jsonb_build_object('kind','course','goal','Draft a useful checking course')); pr:=(r->>'id')::uuid;
 assert lms_claim_agent(pr,o2) is null,'Cross tenant agent claim';
 assert lms_claim_agent(pr,o1) is not null,'Agent lease missing';
 assert lms_claim_agent(pr,o1) is null,'Agent claimed twice';
 update lms_agent_runs set state='needs_review',proposal=content,lease_token=null,lease_until=null where id=pr;
 r:=lms_command(m1,'agent.approve',jsonb_build_object('id',pr));
 assert exists(select 1 from lms_courses where id=(r->>'id')::uuid),'Approved draft missing';
 assert not exists(select 1 from lms_course_versions where course_id=(r->>'id')::uuid),'Agent approval auto-published';
 assert lms_command(m1,'agent.approve',jsonb_build_object('id',pr))=r,'Agent approval not idempotent';
end $$;
select 'LMS tenant isolation, idempotency, publishing, client consent, learning, grading and evidence checks passed' as result;
rollback;
