import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service | AIOPSOS",
  description: "Terms of Service for the AIOPSOS enterprise AI adoption platform.",
};

export default function TermsPage() {
  return (
    <article className="prose prose-neutral dark:prose-invert max-w-none">
      <h1 className="text-3xl font-bold tracking-tight">Terms of Service</h1>
      <p className="text-sm text-muted-foreground">Last updated: 24 February 2026</p>

      <p>
        Welcome to AIOPSOS. These Terms of Service (&quot;Terms&quot;) govern your access
        to and use of the AIOPSOS platform, website, APIs, and related services
        (collectively, the &quot;Service&quot;) operated by AIOPSOS (&quot;we&quot;, &quot;us&quot;, or &quot;our&quot;).
        By creating an account or using the Service, you agree to be bound by
        these Terms. If you do not agree, do not use the Service.
      </p>

      <h2>1. Definitions</h2>
      <ul>
        <li>
          <strong>&quot;Account&quot;</strong> means your registered user account on the
          Service.
        </li>
        <li>
          <strong>&quot;Organisation&quot;</strong> means the company, team, or entity you
          associate with your Account.
        </li>
        <li>
          <strong>&quot;User Content&quot;</strong> means any data, text, files, prompts,
          assessment responses, or other material you submit to the Service.
        </li>
        <li>
          <strong>&quot;AI Output&quot;</strong> means any text, recommendations, roadmaps,
          scores, or other content generated by the Service&apos;s AI models.
        </li>
        <li>
          <strong>&quot;Subscription&quot;</strong> means a paid plan granting access to
          premium features and usage quotas.
        </li>
      </ul>

      <h2>2. Eligibility &amp; Account Registration</h2>
      <p>
        You must be at least 18 years old and have the authority to bind your
        Organisation to these Terms. When registering, you agree to provide
        accurate, current, and complete information. You are responsible for
        safeguarding your credentials and for all activity under your Account.
      </p>

      <h2>3. Use of the Service</h2>
      <h3>3.1 Permitted Use</h3>
      <p>
        You may use the Service for lawful business purposes, including AI
        maturity assessments, generating recommendations, building adoption
        roadmaps, and interacting with AI models through the chat interface.
      </p>

      <h3>3.2 Prohibited Conduct</h3>
      <p>You agree not to:</p>
      <ul>
        <li>Use the Service for any unlawful, harmful, or fraudulent purpose.</li>
        <li>
          Attempt to reverse-engineer, decompile, or extract source code from the
          Service.
        </li>
        <li>
          Interfere with, disrupt, or impose an unreasonable burden on the
          Service&apos;s infrastructure.
        </li>
        <li>
          Circumvent usage limits, quotas, or access controls, including rate
          limits.
        </li>
        <li>
          Submit content that is defamatory, obscene, or infringes third-party
          rights.
        </li>
        <li>
          Use AI Output in a manner that misrepresents it as human-authored
          professional advice (legal, medical, financial, etc.).
        </li>
        <li>
          Share or redistribute your account credentials or allow unauthorised
          third parties to access the Service through your Account.
        </li>
      </ul>

      <h2>4. AI-Generated Content</h2>
      <p>
        The Service uses third-party AI models (including those from OpenAI,
        Anthropic, Google, and Mistral) to generate recommendations, scores,
        roadmaps, policy drafts, and conversational responses. You acknowledge
        that:
      </p>
      <ul>
        <li>
          AI Output is generated algorithmically and may contain inaccuracies,
          biases, or errors.
        </li>
        <li>
          AI Output does not constitute professional advice and should not be
          relied upon as a sole basis for business decisions.
        </li>
        <li>
          You are solely responsible for reviewing, validating, and acting upon
          AI Output.
        </li>
        <li>
          We do not guarantee the accuracy, completeness, or fitness for purpose
          of any AI Output.
        </li>
      </ul>

      <h2>5. Intellectual Property</h2>
      <h3>5.1 Our IP</h3>
      <p>
        The Service, its design, underlying technology, branding, and all
        related intellectual property rights belong to AIOPSOS. These Terms do
        not grant you any ownership rights in the Service.
      </p>

      <h3>5.2 Your Content</h3>
      <p>
        You retain ownership of your User Content. By submitting User Content,
        you grant us a limited, non-exclusive, worldwide licence to process,
        store, and transmit it solely for the purpose of operating and improving
        the Service.
      </p>

      <h3>5.3 AI Output Ownership</h3>
      <p>
        Subject to the rights of underlying AI model providers, you own the AI
        Output generated from your prompts and data. We do not claim ownership
        of AI Output produced for you.
      </p>

      <h2>6. Subscriptions &amp; Billing</h2>
      <p>
        Certain features require a paid Subscription. Billing is handled through
        Stripe. By subscribing, you agree to:
      </p>
      <ul>
        <li>
          Pay all fees associated with your chosen plan, including per-seat
          charges where applicable.
        </li>
        <li>
          Automatic renewal at the end of each billing cycle unless cancelled
          before the renewal date.
        </li>
        <li>
          Provide accurate billing information and keep it up to date.
        </li>
      </ul>
      <p>
        Refunds are handled on a case-by-case basis. Downgrading or cancelling a
        Subscription does not entitle you to a refund for the current billing
        period.
      </p>

      <h2>7. Free Trials</h2>
      <p>
        We may offer free trial periods for premium plans. At the end of a trial,
        your account will revert to the free tier unless you subscribe. We
        reserve the right to modify or discontinue trials at any time.
      </p>

      <h2>8. Data &amp; Privacy</h2>
      <p>
        Our collection and use of personal data is governed by our{" "}
        <Link href="/privacy" className="text-foreground underline underline-offset-4">
          Privacy Policy
        </Link>
        . By using the Service, you consent to such processing and warrant that
        all data provided by you is accurate.
      </p>

      <h2>9. Availability &amp; Support</h2>
      <p>
        We strive to maintain high availability but do not guarantee
        uninterrupted access. The Service may be temporarily unavailable for
        maintenance, updates, or circumstances beyond our control. We provide
        support on a reasonable-efforts basis.
      </p>

      <h2>10. Termination</h2>
      <p>
        You may delete your Account at any time through the settings page. We may
        suspend or terminate your access if you breach these Terms or engage in
        conduct that we reasonably believe is harmful to the Service, other
        users, or third parties. Upon termination:
      </p>
      <ul>
        <li>Your right to access the Service ceases immediately.</li>
        <li>
          We may retain your data for a reasonable period in accordance with our
          Privacy Policy and applicable law.
        </li>
        <li>
          Outstanding payment obligations survive termination.
        </li>
      </ul>

      <h2>11. Disclaimer of Warranties</h2>
      <p>
        THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF
        ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING WARRANTIES OF
        MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
        NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE
        ERROR-FREE, SECURE, OR UNINTERRUPTED.
      </p>

      <h2>12. Limitation of Liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, AIOPSOS SHALL NOT BE LIABLE FOR
        ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES,
        OR ANY LOSS OF PROFITS, DATA, OR GOODWILL, ARISING OUT OF OR RELATED TO
        YOUR USE OF THE SERVICE. OUR TOTAL AGGREGATE LIABILITY SHALL NOT EXCEED
        THE AMOUNT PAID BY YOU TO AIOPSOS IN THE TWELVE (12) MONTHS PRECEDING
        THE CLAIM.
      </p>

      <h2>13. Indemnification</h2>
      <p>
        You agree to indemnify and hold harmless AIOPSOS, its officers,
        directors, employees, and agents from and against any claims, damages,
        losses, liabilities, and expenses (including legal fees) arising out of
        your use of the Service, your User Content, or your violation of these
        Terms.
      </p>

      <h2>14. Modifications</h2>
      <p>
        We may update these Terms from time to time. Material changes will be
        communicated via email or a prominent notice on the Service. Continued
        use after changes take effect constitutes acceptance of the revised
        Terms.
      </p>

      <h2>15. Governing Law &amp; Disputes</h2>
      <p>
        These Terms are governed by and construed in accordance with the laws of
        the jurisdiction in which AIOPSOS is incorporated, without regard to
        conflict of law principles. Any disputes arising from these Terms shall
        be resolved through good-faith negotiation, and failing that, through
        binding arbitration or the courts of competent jurisdiction.
      </p>

      <h2>16. Severability</h2>
      <p>
        If any provision of these Terms is held to be invalid or unenforceable,
        the remaining provisions shall continue in full force and effect.
      </p>

      <h2>17. Entire Agreement</h2>
      <p>
        These Terms, together with our Privacy Policy and Cookie Policy,
        constitute the entire agreement between you and AIOPSOS regarding your
        use of the Service.
      </p>

      <h2>18. Contact</h2>
      <p>
        If you have questions about these Terms, please contact us at{" "}
        <a href="mailto:legal@aiopsos.com" className="text-foreground underline underline-offset-4">
          legal@aiopsos.com
        </a>
        .
      </p>
    </article>
  );
}
