import { NextRequest, NextResponse } from "next/server";
import { Resend } from "resend";
import { marked } from "marked";

const DEMO_RECIPIENT = "ag@experrt.com";

marked.setOptions({ gfm: true });

export async function POST(req: NextRequest) {
  try {
    const apiKey = process.env.RESEND_API_KEY;
    const from = process.env.EMAIL_FROM || "AIOPSOS <noreply@aiopsos.com>";

    if (!apiKey) {
      return NextResponse.json({ error: "Email provider not configured." }, { status: 500 });
    }

    const body = await req.json();
    const subjectRaw = typeof body.subject === "string" ? body.subject.trim() : "";
    const contentRaw = typeof body.content === "string" ? body.content.trim() : "";

    if (!contentRaw) {
      return NextResponse.json({ error: "Email content is required." }, { status: 400 });
    }

    const subject = subjectRaw || "AIOPSOS Flood Response Update";
    const htmlContent = marked.parse(contentRaw, { async: false }) as string;

    const html = `
      <div style="margin:0;padding:0;background:#0d0d0d;font-family:-apple-system,BlinkMacSystemFont,'Inter','Segoe UI',Arial,sans-serif;color:#ececec;">
        <div style="max-width:620px;margin:0 auto;padding:32px 24px;">
          <div style="margin-bottom:28px;">
            <div style="font-size:20px;font-weight:800;letter-spacing:-0.02em;color:#ffffff;">AIOPSOS</div>
            <div style="font-size:12px;color:#a1a1aa;margin-top:4px;">Live Agentic Demo Communication</div>
          </div>
          <div style="background:#141414;border:1px solid rgba(255,255,255,0.09);border-radius:14px;padding:22px;">
            <h2 style="font-size:18px;line-height:1.3;margin:0 0 12px;color:#ffffff;">${escapeHtml(subject)}</h2>
            <p style="font-size:12px;line-height:1.5;color:#a1a1aa;margin:0 0 14px;">Generated by GPT-5.2 agent with live Open-Meteo and Environment Agency data.</p>
            <div style="font-size:14px;line-height:1.65;color:#e5e7eb;">
              <style>h3{font-size:16px;margin:16px 0 8px;color:#ffffff;}strong{font-weight:600;color:#f4f4f5;}ul,ol{margin:8px 0;padding-left:20px;}li{margin:4px 0;}p{margin:8px 0;}</style>
              ${htmlContent}
            </div>
          </div>
          <p style="font-size:11px;line-height:1.5;color:#71717a;margin:14px 4px 0;">
            This message was sent from the Lunch and Learn autonomous response demo.
          </p>
        </div>
      </div>
    `;

    const resend = new Resend(apiKey);
    const { error } = await resend.emails.send({
      from,
      to: DEMO_RECIPIENT,
      subject,
      html,
    });

    if (error) {
      return NextResponse.json({ error: "Failed to send email." }, { status: 500 });
    }

    return NextResponse.json({ success: true, to: DEMO_RECIPIENT });
  } catch {
    return NextResponse.json({ error: "Failed to send email." }, { status: 500 });
  }
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}
