import type { Activity, Band, Mission, Option, Picture } from "../types.ts";
export const PRICE_PENCE = 2000;
export const GENERATION_ALLOWANCE = 30;
export const CONTENT_VERSION = "2026-10-05.1";
export const bands: Record<
  Band,
  {
    name: string;
    ages: string;
    audience: "kids" | "teens";
    duration: string;
    description: string;
    colour: string;
  }
> = {
  explorers: {
    name: "Little Explorers",
    ages: "4–6",
    audience: "kids",
    duration: "25–30 min",
    description:
      "Big discoveries for little imaginations. Play together with a grown-up.",
    colour: "peach",
  },
  inventors: {
    name: "Inventors",
    ages: "7–10",
    audience: "kids",
    duration: "35–45 min",
    description:
      "Meet curious creatures, fix robot mix-ups and bring your ideas to life.",
    colour: "mint",
  },
  creators: {
    name: "Creators",
    ages: "11–13",
    audience: "teens",
    duration: "45–60 min",
    description:
      "Investigate the unexpected. Build worlds and make ideas your own.",
    colour: "lilac",
  },
  studio: {
    name: "Future Studio",
    ages: "14–16",
    audience: "teens",
    duration: "60–75 min",
    description:
      "Your interests. Your projects. Learn to make AI useful on your terms.",
    colour: "blue",
  },
};
const o = (text: string, picture?: Picture): Option => ({
  id: text,
  text,
  picture,
});
const choose = (
  title: string,
  intro: string,
  instruction: string,
  options: (string | [string, Picture])[],
  correct: number,
  feedback: string,
  hint: string,
): Activity => ({
  id: "",
  title,
  intro,
  instruction,
  kind: "choose",
  options: options.map((v) => (typeof v === "string" ? o(v) : o(...v))),
  correct: [
    typeof options[correct] === "string"
      ? (options[correct] as string)
      : (options[correct] as [string, Picture])[0],
  ],
  feedback,
  hint,
});
const sort = (
  title: string,
  intro: string,
  categories: [string, string],
  items: [string, Picture, 0 | 1][],
  feedback: string,
): Activity => ({
  id: "",
  title,
  intro,
  instruction:
    "Choose a group for each picture. You can change your choices before checking.",
  kind: "sort",
  categories,
  options: items.map(([t, p]) => o(t, p)),
  correct: items.map(([, , c]) => String(c)),
  feedback,
  hint: "Look at each item on its own. Use the group names to decide where it belongs.",
});
const order = (
  title: string,
  intro: string,
  steps: string[],
  feedback: string,
): Activity => ({
  id: "",
  title,
  intro,
  instruction:
    "Put the steps in order. Tap a step to add it; tap it again to remove it.",
  kind: "order",
  options: [...steps.slice(1), steps[0]].map((t) => o(t)),
  correct: steps,
  feedback,
  hint: "Think about what must happen first, and what you need to check before you finish.",
});
const evidence = (
  title: string,
  intro: string,
  facts: string[],
  claims: string[],
  correct: number[],
  feedback: string,
): Activity => ({
  id: "",
  title,
  intro,
  instruction:
    "Select every claim that the evidence supports. Leave unsupported claims unselected.",
  kind: "evidence",
  options: claims.map((t) => o(t)),
  correct: correct.map((i) => claims[i]),
  evidence: facts,
  feedback,
  hint: "Match each claim to a specific fact in the evidence. A confident sentence can still be unsupported.",
});
const scene = (
  title: string,
  intro: string,
  options: [string, Picture][],
  required: number[],
  feedback: string,
): Activity => ({
  id: "",
  title,
  intro,
  instruction:
    "Choose the pieces your creation needs. Select a piece again to remove it.",
  kind: "scene",
  options: options.map((v) => o(...v)),
  correct: required.map((i) => options[i][0]),
  feedback,
  hint: "Check every requirement in the mission before choosing your pieces.",
});
function mission(
  band: Band,
  number: number,
  title: string,
  summary: string,
  outcome: string,
  activities: Activity[],
  project: Mission["project"],
  aiBrief?: string,
): Mission {
  return {
    band,
    number,
    title,
    summary,
    outcome,
    slug: title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/-$/, ""),
    skill: [
      "Understand AI",
      "Give clear instructions",
      "Create with AI",
      "Check AI answers",
      "Protect information",
      "Apply your skills",
    ][number - 1],
    introduction: `${summary} ${band === "explorers" ? "Ask a grown-up to read and play with you. " : ""}You will ${outcome.charAt(0).toLowerCase() + outcome.slice(1)}. Pip is a fictional robot character who helps explain the game.`,
    takeaway: outcome,
    activities: activities.map((a, i) => ({ ...a, id: `chapter-${i + 1}` })),
    project,
    aiBrief,
    version: CONTENT_VERSION,
  };
}
const project = (
  title: string,
  prompt: string,
  checks: string[],
  offline: string,
): Mission["project"] => ({ title, prompt, checks, offline });
export const missions: Mission[] = [
  mission(
    "explorers",
    1,
    "Robot Sorting Picnic",
    "Pip is packing a picnic but has mixed up the fruit and things to wear.",
    "Use examples to sort things and notice when a guess is wrong",
    [
      sort(
        "Pack the picnic",
        "Food goes in the basket. Things to wear go in the bag.",
        ["Food", "Things to wear"],
        [
          ["Apple", "apple", 0],
          ["Carrot", "carrot", 0],
          ["Boots", "boots", 1],
        ],
        "Apples and carrots are food. Boots go on your feet. You checked each picture.",
      ),
      choose(
        "Pip makes a guess",
        "Pip saw two round apples and guessed that every round thing is food.",
        ["Which picture shows why this guess can fail?"].join(""),
        [
          ["Another apple", "apple"],
          ["The moon", "moon"],
          ["A carrot", "carrot"],
        ],
        1,
        "The moon is round, but we cannot put it in our lunch. Examples do not make every guess right.",
        "Find something round that is not food.",
      ),
      scene(
        "A picnic for two",
        "Choose food and something that protects your feet. Leave the moon in the sky.",
        [
          ["Apple", "apple"],
          ["Boots", "boots"],
          ["Moon", "moon"],
        ],
        [0, 1],
        "Your picnic has food and footwear. You checked what each thing is for.",
      ),
      sort(
        "Your turn: a new basket",
        "Now sort new things without Pip helping.",
        ["For eating", "For wearing"],
        [
          ["Fish", "fish", 0],
          ["Rain boots", "boots", 1],
          ["Another apple", "apple", 0],
        ],
        "You used what the objects are for, rather than trusting their shape.",
      ),
    ],
    project(
      "My sorting mat",
      "Draw two groups of things. Tell your grown-up why each thing belongs there.",
      ["I made two groups.", "I explained one choice."],
      "Find four safe objects at home and sort them with a grown-up.",
    ),
  ),
  mission(
    "explorers",
    2,
    "Robot Rescue",
    "Pip needs clear directions to reach the treehouse.",
    "Give instructions in order and fix a wrong step",
    [
      order(
        "Across the river",
        "The bridge comes before the treehouse. Pip starts at the picnic blanket.",
        ["Leave the blanket", "Cross the bridge", "Walk to the treehouse"],
        "Pip followed your steps in order. This game follows fixed instructions; it does not learn by itself.",
      ),
      choose(
        "A missing step",
        "Pip was told to reach the treehouse but the river is in the way.",
        "Which instruction helps?",
        ["Be clever", "Use the bridge", "Go somewhere"],
        1,
        "Use the bridge names a clear action Pip can follow.",
        "Name the way across the river.",
      ),
      order(
        "Repair the journey",
        "Pip must fetch a key before opening the workshop.",
        ["Pick up the key", "Open the workshop", "Put the key away"],
        "Getting the key first makes the next step possible.",
      ),
      order(
        "Your turn: plant a seed",
        "Help Pip plant a seed in an empty pot.",
        [
          "Put soil in the pot",
          "Place the seed in the soil",
          "Add a little water",
        ],
        "You gave a new set of instructions in an order that works.",
      ),
    ],
    project(
      "My direction cards",
      "Draw three steps for a small task. Ask your grown-up to follow them exactly.",
      ["My steps are in order.", "I tested my instructions."],
      "Try giving directions to a toy across a table. Keep it away from the edge.",
    ),
  ),
  mission(
    "explorers",
    3,
    "Story Garden",
    "Choose picture pieces to tell a story about a lost robot.",
    "Make a story with a beginning, a problem and an ending",
    [
      scene(
        "Meet your character",
        "Our story needs a robot and a garden. Choose both.",
        [
          ["Robot", "robot"],
          ["Garden tree", "tree"],
          ["Moon", "moon"],
        ],
        [0, 1],
        "You chose who the story is about and where it happens.",
      ),
      choose(
        "Something happens",
        "The robot cannot find its key.",
        "Which picture introduces that problem?",
        [
          ["A missing key", "key"],
          ["A sunny sky", "sun"],
          ["A flower", "flower"],
        ],
        0,
        "The missing key gives the character a problem to solve.",
        "Choose the thing the robot is looking for.",
      ),
      order(
        "Tell the story",
        "Put the picture-story events in order.",
        [
          "A robot arrives in a garden",
          "The robot loses a key",
          "A friend helps find the key",
        ],
        "The events connect. These story pieces were written in advance, not generated by AI.",
      ),
      scene(
        "Your turn: a rainy ending",
        "Make an ending where the robot gets home safely in the rain. Choose protection for its feet and a home.",
        [
          ["Rain boots", "boots"],
          ["Home", "home"],
          ["Picnic apple", "apple"],
        ],
        [0, 1],
        "Your ending fits the rainy setting and gets the robot home.",
      ),
    ],
    project(
      "My picture story",
      "Draw your own ending. Tell a grown-up what happened first and what changed.",
      ["My character has a problem.", "My ending helps solve it."],
      "Act out your story with toys or drawings.",
    ),
  ),
  mission(
    "explorers",
    4,
    "Silly Robot Detective",
    "Pip has muddled some labels. Look closely and help put them right.",
    "Check a claim against something you can see",
    [
      choose(
        "Look at the picture",
        "The evidence picture is a carrot. Pip calls it a boot.",
        "What is in the evidence picture?",
        [
          ["Carrot", "carrot"],
          ["Boot", "boots"],
          ["Moon", "moon"],
        ],
        0,
        "Looking at the picture helps you check Pip’s words. A robot character can make mistakes.",
        "Look for the vegetable.",
      ),
      scene(
        "Check the picnic",
        "Our evidence says the basket holds one apple and one carrot. Choose what is really inside.",
        [
          ["Apple", "apple"],
          ["Carrot", "carrot"],
          ["Moon", "moon"],
        ],
        [0, 1],
        "Both pieces match the evidence. The moon was an extra claim.",
      ),
      choose(
        "We do not know yet",
        "A closed box has no label. Pip says a star is inside, but nobody has opened it.",
        "What should we do?",
        [
          "Say Pip must be right",
          "Ask a grown-up to help check",
          "Pretend we saw it",
        ],
        1,
        "We need to look for evidence before saying what is inside.",
        "Nobody has seen inside yet.",
      ),
      choose(
        "Your turn: a new mix-up",
        "The picture shows the sun. Pip says it is the moon.",
        "Choose the label that matches.",
        [
          ["Sun", "sun"],
          ["Moon", "moon"],
          ["Tree", "tree"],
        ],
        0,
        "You checked a new claim by looking at the evidence.",
        "Look for the bright daytime star.",
      ),
    ],
    project(
      "My detective drawing",
      "Draw a silly mistake and its correction. Tell a grown-up how you knew.",
      ["I spotted a mistake.", "I explained what I checked."],
      "Ask a grown-up to give a toy the wrong name. Correct it together.",
    ),
  ),
  mission(
    "explorers",
    5,
    "Private Treasure",
    "Some information belongs in your private treasure chest.",
    "Recognise private information and ask a trusted adult before sharing",
    [
      sort(
        "Fill the treasure chest",
        "We can use pretend story ideas in this game. Real details about you need a trusted adult.",
        ["Pretend story idea", "Ask a trusted adult"],
        [
          ["An imaginary moon garden", "moon", 0],
          ["Your home address", "home", 1],
          ["A made-up robot", "robot", 0],
        ],
        "Pretend ideas let us play without giving away real details about you.",
      ),
      choose(
        "A question on a screen",
        "A game asks where you live.",
        "What should you do?",
        [
          "Type your address",
          "Ask your trusted grown-up",
          "Guess another child’s address",
        ],
        1,
        "Your grown-up can help decide what information a service really needs.",
        "Your address is private information.",
      ),
      scene(
        "A pretend character",
        "Choose details for a made-up robot. Leave out a real password.",
        [
          ["Robot with wings", "wings"],
          ["Lives on the moon", "moon"],
          ["Your password", "key"],
        ],
        [0, 1],
        "Your pretend robot has a story without sharing a real secret.",
      ),
      choose(
        "Your turn: a secret code",
        "Someone in a game asks for the code that opens your account.",
        "What will you do?",
        [
          "Share the code",
          "Stop and tell a trusted adult",
          "Send a friend’s code",
        ],
        1,
        "Account codes stay private. A trusted adult can help.",
        "A code that opens an account is a secret.",
      ),
    ],
    project(
      "My privacy shield",
      "Draw a shield with a pretend character on it. Name a trusted adult you can ask for help, without typing their name here.",
      ["I know a private detail.", "I know who to ask for help."],
      "Practise saying “I will ask my grown-up first”.",
    ),
  ),
  mission(
    "explorers",
    6,
    "My Helpful Invention",
    "Design a make-believe machine that helps care for a plant.",
    "Explain a helpful job and test instructions with an adult",
    [
      choose(
        "Choose a useful job",
        "Our plant needs care.",
        "Which job would help it?",
        ["Paint the sky", "Remind us to check the soil", "Hide the plant"],
        1,
        "Checking the soil helps a grown-up decide whether the plant needs water.",
        "Think about what the plant needs.",
      ),
      scene(
        "Build the reminder",
        "Choose a plant to check and a reminder picture.",
        [
          ["Plant", "flower"],
          ["Reminder star", "star"],
          ["Flying fish", "fish"],
        ],
        [0, 1],
        "Your invention has a clear job: remind someone to check the plant.",
      ),
      order(
        "Try the instructions",
        "The machine is a pretend reminder, not a real plant expert.",
        [
          "Look at the plant",
          "Ask a grown-up to check the soil",
          "Water only if the grown-up says it needs it",
        ],
        "A person checks what is needed before acting.",
      ),
      choose(
        "Your turn: something changed",
        "The soil is already wet. Your pretend machine says to add water.",
        "What should you do?",
        [
          "Add lots of water",
          "Ask your grown-up and check",
          "Ignore the plant forever",
        ],
        1,
        "A useful helper still needs checking when the situation changes.",
        "Think about the wet soil.",
      ),
    ],
    project(
      "My helpful invention",
      "Draw your invention. Tell a grown-up its job, one instruction and one thing a person must check.",
      [
        "I explained its job.",
        "I tested a step.",
        "I know what a person checks.",
      ],
      "Act as the machine while your grown-up tests your instructions.",
    ),
  ),
  mission(
    "inventors",
    1,
    "Train the Creature Sorter",
    "The island’s creature sorter learned from too few examples. Help it make better guesses.",
    "Choose varied examples and test a prediction on something new",
    [
      sort(
        "A useful starting set",
        "Group creatures by where they live, not by colour.",
        ["Water", "Land"],
        [
          ["Pond fish", "fish", 0],
          ["Forest robot", "robot", 1],
          ["River fish", "fish", 0],
        ],
        "The labels describe the task we want the sorter to learn.",
      ),
      choose(
        "A surprising mistake",
        "The sorter saw only blue water creatures. It calls a blue forest creature a water creature.",
        "What would improve its examples?",
        [
          "More copies of the same blue fish",
          "Water and land creatures in different colours",
          "Only red land creatures",
        ],
        1,
        "Varied examples make colour a less misleading clue. Real AI learns patterns from examples; this game shows a simplified version.",
        "Break the link between colour and habitat.",
      ),
      evidence(
        "Test somewhere new",
        "Use these habitat notes to check the sorter.",
        ["Mossling lives in a forest.", "Ripplefin lives in a river."],
        [
          "Mossling belongs on land.",
          "Every green creature lives on land.",
          "Ripplefin belongs in water.",
        ],
        [0, 2],
        "The notes support two specific conclusions, not a rule about all green creatures.",
      ),
      choose(
        "Your turn: unknown creature",
        "A new creature has no habitat notes. The sorter guesses water.",
        "What should you record?",
        ["Definitely water", "A guess that needs checking", "Definitely land"],
        1,
        "An unfamiliar example can expose a limit. Record uncertainty rather than inventing a fact.",
        "What evidence do you have about this creature?",
      ),
    ],
    project(
      "My creature test cards",
      "Invent two creatures with different colours and habitats. Write a test the sorter might get wrong.",
      ["My examples vary.", "My test includes a new creature."],
      "Ask someone to sort your cards and explain the clues they used.",
    ),
  ),
  mission(
    "inventors",
    2,
    "Creature Creator",
    "An explorer needs a creature that can travel through a rainy forest. Help the description match the job.",
    "Describe requirements clearly and improve a mismatched result",
    [
      scene(
        "Ready for the rainforest",
        "The creature needs rain boots for puddles and leaf camouflage. Choose both.",
        [
          ["Rain boots", "boots"],
          ["Leaf camouflage", "leaf"],
          ["Sun wings", "wings"],
        ],
        [0, 1],
        "Both choices meet the explorer’s requirements. The pieces are authored examples, not live AI generation.",
      ),
      choose(
        "Repair the description",
        "“Make a cool creature” produced a bird without boots.",
        "Which request is clearer?",
        [
          "Make it much cooler",
          "Make a forest creature with rain boots and leaf camouflage",
          "Make any animal",
        ],
        1,
        "The request names the setting and both features, so the result can be checked.",
        "Name what the explorer actually needs.",
      ),
      evidence(
        "Inspect the result",
        "Compare the request with the illustrator’s notes.",
        [
          "Requested: rain boots and leaf camouflage.",
          "Result: leaf body, bare feet and a long tail.",
        ],
        [
          "The result includes camouflage.",
          "The result includes boots.",
          "The result needs a repair to its feet.",
        ],
        [0, 2],
        "The leaf body fits. Bare feet do not meet the boots requirement.",
      ),
      scene(
        "Your turn: moon explorer",
        "A new explorer needs a creature with moon boots and a star-shaped signal. Leave out forest camouflage.",
        [
          ["Moon boots", "boots"],
          ["Star signal", "star"],
          ["Leaf camouflage", "leaf"],
        ],
        [0, 1],
        "You transferred the skill to a different setting and checked the new requirements.",
      ),
    ],
    project(
      "My creature card",
      "Describe your creature’s setting and two useful features. Explain one improvement you made.",
      [
        "I named the setting.",
        "I included two features.",
        "I checked the result.",
      ],
      "Draw the creature and ask someone to match it to your description.",
    ),
  ),
  mission(
    "inventors",
    3,
    "Comic Workshop",
    "Build a three-panel comic about a robot who learns to ask for clearer instructions.",
    "Create and revise a story so its events connect",
    [
      scene(
        "Choose the opening",
        "Our comic begins with a robot at a treehouse. Choose the character and setting.",
        [
          ["Robot", "robot"],
          ["Treehouse", "tree"],
          ["Fish", "fish"],
        ],
        [0, 1],
        "A clear opening helps the reader understand the story.",
      ),
      order(
        "Connect the panels",
        "Arrange the story so each event leads to the next.",
        [
          "Pip is asked to fetch “that thing”",
          "Pip asks which thing is needed",
          "The inventor names the key and Pip finds it",
        ],
        "The character solves the problem by asking for useful detail.",
      ),
      choose(
        "Revise the middle",
        "The middle panel says “Pip did stuff”.",
        "Which replacement helps the reader?",
        [
          "Pip asks, “Do you mean the workshop key?”",
          "Something amazing happened",
          "It was very nice",
        ],
        0,
        "The new line shows the action that solves the problem. These comic pieces were written in advance.",
        "Show the question Pip asks.",
      ),
      order(
        "Your turn: a new comic",
        "A robot waters the wrong plant because the instruction was unclear.",
        [
          "The gardener says “water that plant”",
          "The robot asks which pot needs water",
          "The gardener points to the dry pot",
        ],
        "You created a different story with a clear problem and useful clarification.",
      ),
    ],
    project(
      "My three-panel comic",
      "Draw or describe three panels. Include a question that makes an instruction clearer.",
      [
        "My events connect.",
        "A character asks for detail.",
        "I revised one panel.",
      ],
      "Read your comic aloud with someone taking each character’s part.",
    ),
  ),
  mission(
    "inventors",
    4,
    "Fact Detective",
    "The island guide sounds certain, but some of its facts are mixed up.",
    "Check an answer against supplied evidence and correct unsupported claims",
    [
      evidence(
        "The opening-hours mystery",
        "Check the guide against the noticeboard.",
        ["Workshop opens at 10 am.", "Garden opens at 9 am."],
        [
          "Both places open at 9 am.",
          "The workshop opens at 10 am.",
          "The garden opens before the workshop.",
        ],
        [1, 2],
        "Two claims match the noticeboard. The workshop does not open at 9.",
      ),
      choose(
        "A missing fact",
        "The guide says the workshop has a café. The noticeboard says nothing about food.",
        "What can you conclude?",
        [
          "There is definitely a café",
          "There is definitely no café",
          "The noticeboard does not tell us",
        ],
        2,
        "Missing evidence does not prove either claim. We need another reliable source.",
        "Separate “not mentioned” from “not true”.",
      ),
      order(
        "Repair the guide",
        "You found a wrong opening time.",
        [
          "Read the noticeboard",
          "Compare the guide’s time",
          "Replace the wrong time and name the source",
        ],
        "The correction is supported by something another person can check.",
      ),
      evidence(
        "Your turn: the ferry",
        "Investigate a new timetable.",
        ["First ferry: 11 am.", "Last ferry: 4 pm.", "No service on Mondays."],
        [
          "The ferry runs on Mondays.",
          "The first ferry is at 11 am.",
          "The timetable lists a 4 pm last ferry.",
        ],
        [1, 2],
        "You used the new evidence and rejected the unsupported Monday trip.",
      ),
    ],
    project(
      "My corrected fact file",
      "Write one wrong claim, its correction and the evidence that supports your change.",
      [
        "I quoted the claim.",
        "I checked evidence.",
        "I explained my correction.",
      ],
      "Ask someone to check your correction using the same evidence.",
    ),
  ),
  mission(
    "inventors",
    5,
    "Secret Shield",
    "A fictional character has put private details into a request for a story. Help make the request safer.",
    "Replace personal details with fictional details before using an AI tool",
    [
      sort(
        "Inspect the request",
        "The character wants a story about a space garden.",
        ["Useful pretend detail", "Remove private detail"],
        [
          ["A garden on the moon", "moon", 0],
          ["Real home address", "home", 1],
          ["Account password", "key", 1],
          ["A purple robot", "robot", 0],
        ],
        "The story needs creative detail, not a real address or account secret.",
      ),
      choose(
        "Repair the request",
        "“Use my real school name and class timetable in a robot adventure.”",
        "Which replacement keeps the idea?",
        [
          "Use a fictional school on an imaginary planet",
          "Use a friend’s real timetable",
          "Add my address too",
        ],
        0,
        "Fictional details preserve the story without exposing someone’s routine.",
        "Keep the creative idea and remove identifying details.",
      ),
      scene(
        "Build a safe story kit",
        "Choose two fictional details for the story.",
        [
          ["Imaginary star school", "star"],
          ["Robot gardener", "robot"],
          ["Real account key", "key"],
        ],
        [0, 1],
        "The kit gives the writer useful ideas without an account secret.",
      ),
      choose(
        "Your turn: a photo request",
        "A new game asks for a photo showing your school badge.",
        "What will you do?",
        [
          "Upload it immediately",
          "Ask a trusted adult before sharing",
          "Upload a friend’s photo instead",
        ],
        1,
        "Photos can reveal identifying details. A trusted adult can help decide whether sharing is needed.",
        "Look for information about where someone goes to school.",
      ),
    ],
    project(
      "My privacy repair card",
      "Write a fictional unsafe request, then rewrite it using made-up details. Do not include real secrets.",
      ["I used fictional examples.", "I removed identifying details."],
      "Practise explaining why an imaginary detail can work just as well.",
    ),
  ),
  mission(
    "inventors",
    6,
    "Hobby Helper",
    "Plan a paper-rocket challenge for a fictional club, then test whether the plan is usable.",
    "Give a useful task, set limits and check a simple plan",
    [
      choose(
        "Choose the job",
        "The club has paper, pencils and 20 minutes.",
        "Which request fits?",
        [
          "Plan a paper-rocket drawing challenge using paper and pencils in 20 minutes",
          "Build a real rocket today",
          "Buy lots of supplies",
        ],
        0,
        "The request includes the goal, materials and time limit.",
        "Use only the supplies and time given.",
      ),
      order(
        "Make time to test",
        "Arrange the activity.",
        [
          "Explain the drawing challenge",
          "Draw a paper-rocket design",
          "Check the design against the instructions",
          "Share one improvement",
        ],
        "Testing before sharing gives you a chance to improve the work.",
      ),
      evidence(
        "Spot the mismatch",
        "Check the suggested plan.",
        ["Available materials: paper and pencils.", "Time limit: 20 minutes."],
        [
          "A plan requiring paint needs changing.",
          "A 60-minute activity fits the limit.",
          "A pencil sketch uses available materials.",
        ],
        [0, 2],
        "Materials and time are useful checks, even when a plan sounds exciting.",
      ),
      choose(
        "Your turn: a different club",
        "A fictional nature club has crayons, paper and 15 minutes.",
        "Which plan fits?",
        [
          "Draw a leaf and label its shapes using crayons for 15 minutes",
          "Take a two-hour forest trip",
          "Make a sculpture with clay",
        ],
        0,
        "You applied the same planning skill to a new hobby.",
        "Check both materials and duration.",
      ),
    ],
    project(
      "My hobby challenge",
      "Write a pretend club plan with materials, time, steps and one check. Explain a change after testing it.",
      ["I set limits.", "I tested the steps.", "I improved the plan."],
      "Try the paper activity with a grown-up or friend.",
    ),
  ),
  mission(
    "creators",
    1,
    "Inside the Guessing Machine",
    "A fictional creature classifier seems accurate until it meets unfamiliar examples. Investigate why.",
    "Explain how examples influence predictions and test a model’s limits",
    [
      choose(
        "A misleading shortcut",
        "Training examples show every water creature as blue and every land creature as orange.",
        "What might the model learn?",
        [
          "Colour may become an unreliable shortcut",
          "It understands every habitat",
          "Its guesses must always be correct",
        ],
        0,
        "A model can use a pattern in the examples that does not hold in the wider world.",
        "Look for an accidental pattern in the examples.",
      ),
      sort(
        "Build a better set",
        "Label new examples using their documented habitats.",
        ["Water habitat", "Land habitat"],
        [
          ["Orange reef swimmer", "fish", 0],
          ["Blue woodland crawler", "boots", 1],
          ["Green river glider", "leaf", 0],
        ],
        "The new examples vary colour while keeping habitat labels accurate. This game simulates training choices.",
      ),
      evidence(
        "Read the test log",
        "Check what the results establish.",
        [
          "The model correctly classified 8 of 10 unseen creatures.",
          "Both mistakes were creatures unlike the training examples.",
        ],
        [
          "It was correct on every test.",
          "It made two mistakes.",
          "Unfamiliar examples exposed a weakness.",
        ],
        [1, 2],
        "A small test provides evidence about those cases, not a guarantee about all future predictions.",
      ),
      choose(
        "Your turn: a music sorter",
        "A music sorter learned only from fast songs labelled happy.",
        "Which test best probes its shortcut?",
        [
          "Another fast happy song",
          "A fast sad song with a checked label",
          "A copy of a training song",
        ],
        1,
        "Changing the relationship between speed and mood tests the suspected shortcut.",
        "Find a case where the shortcut would fail.",
      ),
    ],
    project(
      "My model test report",
      "Describe the examples, suspected shortcut, new test and what the result would tell you.",
      ["I separated examples from rules.", "I designed an unfamiliar test."],
      "Try your classification rule on three invented examples.",
    ),
  ),
  mission(
    "creators",
    2,
    "Prompt Repair Shop",
    "Repair a vague request for a fictional museum sign and compare the results.",
    "Write a clear request and check whether its output meets the brief",
    [
      choose(
        "Diagnose the request",
        "“Write something about space” produced a long technical essay. The museum needs a short sign for young visitors.",
        "Which detail matters most?",
        [
          "A 60-word sign for ages 8–10 about the Moon",
          "Make it better",
          "Use impressive words",
        ],
        0,
        "Audience, length and topic make the task clear enough to test.",
        "Specify who will read it and what they need.",
      ),
      order(
        "Build and test",
        "Arrange the repair process.",
        [
          "Describe the audience and purpose",
          "Supply checked facts and limits",
          "Generate a draft",
          "Compare the draft with the brief",
        ],
        "The request and the check work together. A polished draft still needs review.",
      ),
      evidence(
        "Check a draft",
        "Use the brief to review a proposed sign.",
        [
          "Brief: at most 60 words.",
          "Use only these facts: the Moon orbits Earth; it reflects sunlight.",
          "Draft: 90 words and a claim that the Moon makes its own light.",
        ],
        [
          "The draft breaks the length limit.",
          "The light claim conflicts with the supplied facts.",
          "The draft meets every requirement.",
        ],
        [0, 1],
        "Both the length and factual claim need repair.",
      ),
      choose(
        "Your turn: a garden sign",
        "A garden needs a 40-word sign using only two supplied plant facts.",
        "Which request is easiest to check?",
        [
          "Write a nice sign",
          "Write at most 40 words for garden visitors using only the two supplied facts",
          "Invent interesting facts",
        ],
        1,
        "The new brief states a measurable limit and a clear evidence boundary.",
        "Make the task testable.",
      ),
    ],
    project(
      "My before-and-after prompt",
      "Save your original request, improved request and one difference you checked in the output.",
      ["I named the audience.", "I set a limit.", "I checked the output."],
      "Read the sign aloud and see whether the intended reader would understand it.",
    ),
    "Create a museum sign for ages 8–10 in at most 60 words. Use only these facts: the Moon orbits Earth and reflects sunlight. Offer a draft, then a short check against those requirements.",
  ),
  mission(
    "creators",
    3,
    "Worldbuilder Studio",
    "Design a fictional world whose details follow its own rules.",
    "Develop an original idea and check generated details for consistency",
    [
      scene(
        "Set the world rules",
        "Our world is a moon garden with plants that glow. Choose its two defining pieces.",
        [
          ["Moon setting", "moon"],
          ["Glowing plants", "flower"],
          ["Ordinary city", "home"],
        ],
        [0, 1],
        "A few clear rules give the world a recognisable identity.",
      ),
      choose(
        "A broken rule",
        "Your world has no oceans. A draft introduces a submarine crossing its ocean.",
        "What is a useful revision?",
        [
          "Ignore the contradiction",
          "Replace the ocean journey with travel through underground tunnels",
          "Delete the whole project",
        ],
        1,
        "The revision keeps the adventure while respecting the world’s rules.",
        "Preserve the idea but repair the conflicting detail.",
      ),
      order(
        "Make it yours",
        "Arrange a creative workflow.",
        [
          "Write your world’s rules",
          "Request a few possible details",
          "Choose and change the details you like",
          "Check the result against your rules",
        ],
        "You make creative decisions rather than accepting every generated suggestion.",
      ),
      evidence(
        "Your turn: the sky library",
        "Check a new setting.",
        [
          "The library floats above the clouds.",
          "Visitors arrive in gliders.",
          "Books stay inside the library.",
        ],
        [
          "A visitor arrives in a glider.",
          "Visitors take books home.",
          "The building is above the clouds.",
        ],
        [0, 2],
        "Two details fit the new world. Taking books home breaks its rule.",
      ),
    ],
    project(
      "My world guide",
      "Describe your setting, three rules and a scene. Identify a suggestion you changed and why.",
      [
        "My rules are clear.",
        "My scene follows them.",
        "I made a creative revision.",
      ],
      "Sketch a map and ask someone to spot a detail that needs explaining.",
    ),
    "Suggest three short scene ideas for a fictional moon garden with glowing plants and no oceans. Use no real people or locations. Help the learner choose and revise an idea; do not write a finished assessed project.",
  ),
  mission(
    "creators",
    4,
    "Rumour Lab",
    "A convincing island news post mixes evidence with invented details. Trace the claims.",
    "Distinguish supported claims, contradictions and missing evidence",
    [
      evidence(
        "Trace the headline",
        "Review the fictional notice.",
        [
          "The studio is closed on Tuesday for repairs.",
          "It reopens on Wednesday at 10 am.",
        ],
        [
          "The studio is closed all week.",
          "It reopens on Wednesday at 10 am.",
          "Repairs are the stated reason for Tuesday’s closure.",
        ],
        [1, 2],
        "The notice supports a one-day closure and gives the reopening time.",
      ),
      choose(
        "A quotation without a source",
        "An AI draft quotes a studio manager, but none of the supplied material contains the quote.",
        "What should you do?",
        [
          "Publish it because it sounds realistic",
          "Remove it or find an authentic source before using it",
          "Invent a source link",
        ],
        1,
        "A convincing quotation needs an authentic source.",
        "Can someone else find the words in the evidence?",
      ),
      order(
        "Repair the post",
        "Put the verification steps in order.",
        [
          "List the checkable claims",
          "Match each claim to a source",
          "Correct or remove unsupported details",
          "Add the sources used",
        ],
        "The process makes the final post easier for another reader to verify.",
      ),
      evidence(
        "Your turn: a new rumour",
        "Check a fictional exhibition update.",
        ["The exhibition has 12 artworks.", "Entry is free on Saturday."],
        [
          "Entry is always free.",
          "There are 12 artworks.",
          "Saturday entry is free.",
        ],
        [1, 2],
        "A claim about Saturday does not establish the price on every other day.",
      ),
    ],
    project(
      "My rumour repair",
      "Write a corrected post using the supplied facts. Explain one unsupported detail you removed.",
      ["I matched claims to evidence.", "I avoided invented quotes."],
      "Ask someone to trace each sentence of your post to a fact.",
    ),
  ),
  mission(
    "creators",
    5,
    "Digital Footprint Escape",
    "Unlock a fictional studio by making sensible choices about information and permissions.",
    "Share only what a task needs and recognise unnecessary permissions",
    [
      sort(
        "Inspect a fictional profile",
        "A writing activity needs creative preferences, not identifying information.",
        ["Useful for the task", "Leave out"],
        [
          ["Favourite fictional genre", "book", 0],
          ["Home address", "home", 1],
          ["Account password", "key", 1],
          ["Imaginary planet setting", "moon", 0],
        ],
        "Creative preferences help the task without exposing account secrets or a home address.",
      ),
      choose(
        "The permission door",
        "A text story tool asks to access your precise location.",
        "What is the best next step?",
        [
          "Allow everything",
          "Decline and ask a trusted adult whether the permission is needed",
          "Share a friend’s location",
        ],
        1,
        "A text story normally does not need your precise location. Question permissions unrelated to the task.",
        "Match the permission to the tool’s purpose.",
      ),
      choose(
        "Someone else’s information",
        "A draft includes a classmate’s full name and private problem.",
        "How can you practise safely?",
        [
          "Use a fictional character and situation",
          "Keep the name but change one letter",
          "Post it publicly",
        ],
        0,
        "A fully fictional example avoids exposing another person’s private situation.",
        "A tiny name change may still identify someone.",
      ),
      choose(
        "Your turn: the public gallery",
        "A tool offers to publish your work and profile automatically.",
        "What should you do first?",
        [
          "Accept without reading",
          "Check what becomes public with your parent and keep it private while deciding",
          "Add your school to the profile",
        ],
        1,
        "Understanding the audience and visible information comes before publishing.",
        "Find out who can see the work.",
      ),
    ],
    project(
      "My permission checklist",
      "Describe three checks you would make before sharing work or granting a tool permission. Use fictional examples.",
      [
        "I considered the purpose.",
        "I considered who can see it.",
        "I protected other people’s details.",
      ],
      "Review an imaginary app permission screen with a trusted adult.",
    ),
  ),
  mission(
    "creators",
    6,
    "Study Quest",
    "Create a revision activity from a small fact pack and test whether it teaches accurately.",
    "Use AI to support practice while checking questions and answers yourself",
    [
      evidence(
        "Start with source material",
        "Use the supplied science notes.",
        [
          "Evaporation changes liquid water into water vapour.",
          "Condensation changes water vapour into liquid water.",
        ],
        [
          "Evaporation turns liquid into vapour.",
          "Condensation turns vapour into liquid.",
          "Both processes are freezing.",
        ],
        [0, 1],
        "Both correct statements follow the notes. Freezing is a different change.",
      ),
      choose(
        "A useful learning request",
        "You want to practise the two processes.",
        "Which request supports your learning?",
        [
          "Give me the answers to my real homework",
          "Ask me one question at a time using these notes, then explain the answer",
          "Make up extra facts",
        ],
        1,
        "A practice question helps you retrieve the idea and learn from feedback.",
        "Choose a request that makes you do the thinking.",
      ),
      order(
        "Test the quiz",
        "Arrange the study loop.",
        [
          "Read the supplied notes",
          "Answer a practice question yourself",
          "Check the answer against the notes",
          "Explain your correction in your own words",
        ],
        "The check and explanation help turn a mistake into learning.",
      ),
      choose(
        "Your turn: a wrong answer key",
        "A generated quiz says condensation turns liquid into vapour. Your notes say the opposite.",
        "What should you do?",
        [
          "Trust the generated key",
          "Correct the key using the notes and explain the change",
          "Memorise both versions",
        ],
        1,
        "You have evidence for correcting the generated answer.",
        "Return to the definition in the notes.",
      ),
    ],
    project(
      "My checked revision cards",
      "Write two questions, their answers and the supporting notes. Explain one check you made.",
      [
        "I answered before checking.",
        "My answers match the notes.",
        "I explained an idea myself.",
      ],
      "Ask someone to try your cards without seeing the answers.",
    ),
    "Create two short practice questions using only: evaporation changes liquid water into water vapour; condensation changes water vapour into liquid water. Include an answer key clearly separated from the questions. Encourage the learner to answer before reading the key.",
  ),
  mission(
    "studio",
    1,
    "Choose the Right Helper",
    "Choose tools for a fictional youth club based on what the task actually requires.",
    "Decide when to use AI, a conventional tool or human judgement",
    [
      sort(
        "Match the task",
        "Consider whether a task needs exact calculation or creative suggestions.",
        ["Calculator or spreadsheet", "AI suggestions to review"],
        [
          ["Add a fixed budget", "key", 0],
          ["Brainstorm fictional event names", "star", 1],
          ["Calculate ticket totals", "book", 0],
        ],
        "Exact arithmetic has dependable conventional tools. Open-ended suggestions can benefit from AI with review.",
      ),
      choose(
        "A decision involving people",
        "A club must resolve a disagreement between two members.",
        "Who should take responsibility?",
        [
          "An AI making the final decision from one message",
          "A responsible person who can listen to both people",
          "A random online poll",
        ],
        1,
        "A person needs to understand the context, hear both sides and take responsibility.",
        "Consider what is missing from a single message.",
      ),
      evidence(
        "Check suitability",
        "The club wants a poster draft.",
        [
          "The date and venue are confirmed.",
          "No member photos have permission for publication.",
        ],
        [
          "AI may help draft wording using the confirmed facts.",
          "Any member photo can be used.",
          "A person must check the final details.",
        ],
        [0, 2],
        "A drafting tool can help without replacing fact-checking or permission decisions.",
      ),
      choose(
        "Your turn: route planning",
        "A trip needs current transport times.",
        "Which approach fits?",
        [
          "Use an old generated timetable without checking",
          "Check the transport operator’s current timetable, then use AI only to help organise verified details",
          "Invent plausible times",
        ],
        1,
        "Current operational information needs an authoritative current source.",
        "Match the source to the freshness the task needs.",
      ),
    ],
    project(
      "My tool-choice guide",
      "Choose three fictional tasks. Explain the tool you would use, why it fits and what a person must check.",
      ["I matched tools to tasks.", "I named a human responsibility."],
      "Ask someone to challenge one of your tool choices.",
    ),
  ),
  mission(
    "studio",
    2,
    "Brief Builder",
    "Turn a messy request into a clear creative brief for a fictional club poster.",
    "Specify an audience, source facts, constraints and checks for an AI draft",
    [
      choose(
        "Find the missing constraints",
        "“Make an exciting poster” leaves the model guessing. The club meets Saturday at 2 pm in the library.",
        "Which brief is usable?",
        [
          "Write at most 50 words for a teen club poster. Use Saturday, 2 pm, library. Do not invent prices.",
          "Make it impressive",
          "Include whatever sounds convincing",
        ],
        0,
        "The brief supplies facts and limits that can be checked.",
        "Include audience, facts and a limit.",
      ),
      order(
        "Build a reliable brief",
        "Arrange the process.",
        [
          "State the purpose and audience",
          "Supply confirmed facts and constraints",
          "Request a specific output format",
          "List the checks for the result",
        ],
        "A brief explains both what to produce and how it will be reviewed.",
      ),
      evidence(
        "Review the result",
        "Compare a draft with the brief.",
        [
          "Brief: Saturday, 2 pm, library; no invented prices.",
          "Draft: Sunday, 2 pm, library; tickets £5.",
        ],
        [
          "The day needs correcting.",
          "The price is unsupported.",
          "The draft meets the brief.",
        ],
        [0, 1],
        "A fluent draft can still change facts and invent details.",
      ),
      choose(
        "Your turn: a podcast intro",
        "A fictional podcast needs a 30-second introduction using only three supplied facts.",
        "Which extra instruction is useful?",
        [
          "Invent expert quotes",
          "Use only the supplied facts and flag any missing information",
          "Guarantee everyone will love it",
        ],
        1,
        "The instruction limits fabrication and makes uncertainty visible.",
        "Keep the draft inside the evidence boundary.",
      ),
    ],
    project(
      "My tested creative brief",
      "Write a brief, save a draft and compare it with at least three requirements. Revise a mismatch.",
      [
        "I provided facts.",
        "I set measurable constraints.",
        "I tested the draft.",
      ],
      "Have someone review the draft using only your brief.",
    ),
    "Draft a fictional teen club poster in at most 50 words. Confirmed facts: Saturday, 2 pm, library. No invented prices, contact details or quotations. Add a short checklist of the facts and word limit.",
  ),
  mission(
    "studio",
    3,
    "Game Concept Studio",
    "Design a small branching story and test whether its choices have meaningful consequences.",
    "Build and revise a playable branching story with consistent rules",
    [
      choose(
        "A meaningful choice",
        "A player reaches a locked observatory.",
        "Which design creates a useful choice?",
        [
          "Two buttons that both silently do the same thing",
          "Search the garden for a key or ask the caretaker for help, each with a different next scene",
          "A button that ends the game unexpectedly",
        ],
        1,
        "Different consequences make the choice understandable and worth testing.",
        "A player should be able to see how the choice matters.",
      ),
      order(
        "Build a small game",
        "Arrange the development loop.",
        [
          "Write the goal and world rules",
          "Draft two branches and their endings",
          "Play through every branch",
          "Repair dead ends and contradictions",
        ],
        "A small complete game can be tested more reliably than an unfinished large one.",
      ),
      evidence(
        "Inspect the branches",
        "Read the game rules and test log.",
        [
          "Rule: players need a key to enter the observatory.",
          "Branch A gives the key before entry.",
          "Branch B enters without finding a key.",
        ],
        [
          "Branch A follows the rule.",
          "Branch B needs revision.",
          "Both branches follow the rule.",
        ],
        [0, 1],
        "Testing both branches reveals a rule violation that one playthrough would miss.",
      ),
      choose(
        "Your turn: an unreachable ending",
        "Your map has a final scene with no incoming choice.",
        "What should you do?",
        [
          "Add a meaningful path to it and test again",
          "Leave it because the writing is good",
          "Add five more endings first",
        ],
        0,
        "An ending must be reachable through the actual choices.",
        "Trace how a player can reach the scene.",
      ),
    ],
    project(
      "My branching text game",
      "Write an opening, two choices and two endings. Record a playtest for each path and one repair.",
      [
        "Both paths are playable.",
        "The rules stay consistent.",
        "I recorded a repair.",
      ],
      "Ask another person to play using only the choices you wrote.",
    ),
    "Suggest a small fictional observatory adventure: one opening, two choices and two endings. Both paths must obtain a key before entering. Keep it under 220 words and include two playtest questions. No executable code or external links.",
  ),
  mission(
    "studio",
    4,
    "Evidence Room",
    "Review an AI-produced brief for a fictional community exhibition before it is shared.",
    "Verify claims and citations and communicate unresolved uncertainty",
    [
      evidence(
        "Audit the brief",
        "Compare the brief’s claims with the source pack.",
        [
          "Source A: exhibition opens 12 June.",
          "Source B: venue capacity is 80 visitors.",
        ],
        [
          "The exhibition opens 12 June.",
          "The venue holds 800 visitors.",
          "Source B states a capacity of 80.",
        ],
        [0, 2],
        "The capacity claim has gained an extra zero. Naming a source does not make a claim accurate.",
      ),
      choose(
        "A citation that goes nowhere",
        "The draft cites “Source C”, which is absent from the supplied pack.",
        "What should you do?",
        [
          "Treat the citation as proof",
          "Locate and inspect a real source or remove the unsupported claim",
          "Create a fake Source C",
        ],
        1,
        "A citation is useful only when it leads to evidence that supports the claim.",
        "Check existence as well as relevance.",
      ),
      order(
        "Resolve a disagreement",
        "Two sources give different opening dates.",
        [
          "Record the conflicting dates",
          "Check source dates and authority",
          "Seek confirmation if the conflict remains",
          "State the confirmed date or clearly mark it unresolved",
        ],
        "When evidence conflicts, the honest result may include uncertainty.",
      ),
      evidence(
        "Your turn: budget claims",
        "Check a new brief.",
        [
          "Confirmed room hire: £100.",
          "Printing quote: £40, awaiting approval.",
        ],
        [
          "Room hire is confirmed at £100.",
          "Every cost is approved.",
          "Printing is quoted at £40 but not approved.",
        ],
        [0, 2],
        "The status of a number matters as well as its value.",
      ),
    ],
    project(
      "My evidence audit",
      "List three claims, their supporting sources and a decision to keep, correct or mark unresolved.",
      [
        "I inspected sources.",
        "I corrected a mismatch.",
        "I recorded uncertainty.",
      ],
      "Ask someone to reproduce one of your checks.",
    ),
  ),
  mission(
    "studio",
    5,
    "Publish with Care",
    "Review a fictional club project for privacy, permission and misleading presentation.",
    "Prepare work for sharing while respecting other people and explaining AI use",
    [
      sort(
        "Review the publication pack",
        "The poster can use approved fictional artwork. Account secrets and private information do not belong in it.",
        ["Suitable for this poster", "Remove from the poster"],
        [
          ["Approved fictional illustration", "flower", 0],
          ["Member’s home address", "home", 1],
          ["Account password", "key", 1],
          ["Confirmed public event time", "sun", 0],
        ],
        "The public poster needs event information, not private account or household details.",
      ),
      choose(
        "A realistic invented image",
        "A generated image makes it look as if a real person attended an event they did not attend.",
        "What is the responsible revision?",
        [
          "Publish it as a documentary photo",
          "Use clearly labelled fictional artwork without misrepresenting a real person",
          "Add a tiny hidden label",
        ],
        1,
        "The presentation should make the fictional nature clear and avoid a false claim about a real person.",
        "Consider what an ordinary viewer would believe.",
      ),
      choose(
        "Someone else’s creative work",
        "A friend’s illustration would improve the poster. They have not agreed to its use.",
        "What should you do?",
        [
          "Ask permission and follow the agreed credit and use conditions",
          "Assume online means free to use",
          "Erase their signature",
        ],
        0,
        "Permission and attribution are part of using someone else’s work respectfully.",
        "Being able to access something is different from having permission.",
      ),
      choose(
        "Your turn: the project note",
        "You used AI for initial wording and then checked and rewrote it.",
        "Which note is accurate?",
        [
          "I created every word without assistance",
          "AI helped with an initial draft; I checked the facts and revised the wording",
          "AI guarantees this is accurate",
        ],
        1,
        "The note describes the actual assistance and your responsibility without overstating either.",
        "Describe what really happened.",
      ),
    ],
    project(
      "My publication check",
      "Write a release checklist covering private details, permissions, factual checks and a truthful AI-use note.",
      [
        "I checked privacy.",
        "I checked permission.",
        "I explained AI assistance.",
      ],
      "Review a fictional poster with someone before sharing it.",
    ),
  ),
  mission(
    "studio",
    6,
    "Make Life Easier",
    "Build a useful plan for a fictional study, hobby or club task and test it against real constraints.",
    "Design a bounded AI-assisted workflow and evaluate whether it helps",
    [
      choose(
        "Define a small useful task",
        "A fictional club spends time turning agreed actions into a checklist.",
        "Which first project is manageable?",
        [
          "Draft a checklist from supplied action notes, then have a person check it",
          "Let AI make every club decision",
          "Automatically message everyone without review",
        ],
        0,
        "A bounded drafting task has clear input, output and a human check.",
        "Choose a task with a result you can inspect.",
      ),
      order(
        "Build the workflow",
        "Arrange the work.",
        [
          "Describe the task and success criteria",
          "Supply fictional notes and limits",
          "Generate a draft checklist",
          "Check every action and improve the instructions",
        ],
        "The workflow keeps responsibility with the person using the result.",
      ),
      evidence(
        "Test the checklist",
        "Compare the output with the agreed notes.",
        [
          "Notes: Alex makes a poster by Friday.",
          "Notes: Sam checks the room booking on Thursday.",
          "Draft: Alex books the room; Sam makes a poster.",
        ],
        [
          "The draft swaps the responsibilities.",
          "The draft is ready to use.",
          "The output needs correcting against the notes.",
        ],
        [0, 2],
        "The names and actions must stay connected. Fluent wording is not enough.",
      ),
      choose(
        "Your turn: measure usefulness",
        "Your revised workflow produces a correct checklist but takes longer than doing it directly.",
        "What should you conclude?",
        [
          "Keep it unchanged because it uses AI",
          "Review whether it helps; simplify it or use the direct method",
          "Claim a time saving anyway",
        ],
        1,
        "A useful project needs evidence of benefit as well as a working demonstration.",
        "Compare the result and effort with the original approach.",
      ),
    ],
    project(
      "My useful project report",
      "Record the task, input, instructions, output, two tests and one limitation. Explain whether the approach helped.",
      [
        "I bounded the task.",
        "I checked two cases.",
        "I evaluated usefulness.",
      ],
      "Ask another person to try your workflow with different fictional notes.",
    ),
    "Turn these fictional club notes into a short checklist: Alex makes a poster by Friday. Sam checks the room booking on Thursday. Preserve responsibilities and dates. Include a verification table and ask the learner to test a changed example.",
  ),
];
export const getMission = (slug: string) =>
  missions.find((m) => m.slug === slug);
export const missionsForBand = (band: Band) =>
  missions.filter((m) => m.band === band);
