import type {DeliveryLiveData} from "@/components/lms/delivery-live";
import { z } from "zod";
import { deliveryCommand } from "@/lib/lms/delivery-server";
import { deliveryInsights, skillResults, type DeliveryWorkspace } from "@/lib/lms/delivery-schema";
import { learningErrorResponse } from "@/lib/lms/server";
const html=(v:unknown)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
const csv=(v:unknown)=>`"${String(v??"").replace(/^[=+@\-\t\r]/,"'$&").replaceAll('"','""')}"`;
export async function GET(request:Request,{params}:{params:Promise<{id:string}>}){
 try {
  const id=z.string().uuid().parse((await params).id);
  const data=await deliveryCommand(id,"get") as DeliveryWorkspace;
  const live=await deliveryCommand(id,"live.get") as DeliveryLiveData;
  const date=new Date().toISOString();
  if(new URL(request.url).searchParams.get("format")==="csv"){
   const rows:unknown[][]=[["Programme","Learner","Assignment","Coursework completed","Latest decision","Skill","Entry (%)","Final (%)","Change (percentage points)","Evidence record IDs","Generated at"]];
   for(const r of data.records){const skills=data.plan?.content?skillResults(r,data.plan.content):[];for(const s of skills.length?skills:[null])rows.push([data.programme.title,r.name,r.id,r.completed_at,r.decisions.at(-1)?.kind,s?.skill,s?.baseline,s?.final,s?.change,s?.evidence.join("; "),date]);}
   return new Response(rows.map(r=>r.map(csv).join(",")).join("\r\n"),{headers:{"Content-Type":"text/csv; charset=utf-8","Content-Disposition":"attachment; filename=programme-progress.csv","Cache-Control":"private, no-store"}});
  }
  const body=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${html(data.programme.title)} | Programme report</title><style>body{font:15px/1.6 system-ui,sans-serif;color:#172132;max-width:1100px;margin:40px auto;padding:0 24px}h1{font-size:32px}h2{margin-top:40px;color:#6244bb}table{border-collapse:collapse;width:100%;margin:20px 0}th,td{text-align:left;border:1px solid #d8dce4;padding:10px;vertical-align:top}small{color:#596474}article{break-inside:avoid;border-top:2px solid #eee;margin-top:32px}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:inherit}a{color:#6244bb}@media print{body{margin:0}a{color:inherit}article{break-inside:auto}}</style></head><body><p>Experrt · Programme evidence report</p><h1>${html(data.programme.title)}</h1><p>${html(data.programme.goal)}</p><small>Generated ${html(date)} · Plan revision ${html(data.plan?.revision||"not prepared")} · View: ${html(data.role)}</small><p>Use your browser’s Print action to save this report as a PDF. Results reflect recorded evidence. Readiness decisions are recommendations; employment decisions remain with the employer.</p>${data.plan?.content?`<h2>Approved scope</h2><p>${html(data.plan.content.brief)}</p><p>Target roles and entry requirements: ${html(data.plan.content.targetRoles)}</p><p>${html(data.plan.content.hours)} learning hours · Plan ${data.plan.released_at?"released":"not released"}</p><p>Criteria are scored from 0 (no evidence) to 4 (strong independent demonstration). Matching skill labels are compared between entry and final assessment. Different evidence conditions may affect comparability.</p>`:""}${data.records.map(r=>{
   const skills=data.plan?.content?skillResults(r,data.plan.content):[];
   return `<article><h2>${html(r.name)}</h2><small>Assignment ${html(r.id)}</small><p>Coursework: ${r.completed_at?`completed ${html(r.completed_at)}`:"in progress"}</p><table><thead><tr><th>Skill</th><th>Entry</th><th>Final</th><th>Change</th></tr></thead><tbody>${skills.map(s=>`<tr><td>${html(s.skill)}</td><td>${s.baseline===null?"Not assessed":s.baseline+"%"}</td><td>${s.final===null?"Not assessed":s.final+"%"}</td><td>${s.change===null?"Not comparable":s.change+" points"}</td></tr>`).join("")||'<tr><td colspan="4">No scored entry or final evidence yet.</td></tr>'}</tbody></table>${data.plan?.content?`<ul>${deliveryInsights(r,data.plan.content).map(i=>`<li>${html(i.label)}${i.evidence.length?`<br><small>Evidence: ${html(i.evidence.join(", "))}</small>`:""}</li>`).join("")}</ul>`:""}<h3>Live training attendance</h3><table><thead><tr><th>Session</th><th>Starts</th><th>Attendance</th></tr></thead><tbody>${live.groups.flatMap(g=>g.sessions.flatMap(session=>session.register.filter(a=>a.assignment_id===r.id).map(a=>`<tr><td>${html(g.title)}: ${html(session.title)}</td><td>${html(session.starts_at)}</td><td>${html(a.status||"Not recorded")}</td></tr>`))).join("")||'<tr><td colspan="3">No linked live-training enrolment recorded.</td></tr>'}</tbody></table><h3>Decisions</h3>${r.decisions.map(d=>`<p><strong>${html(d.kind.replaceAll("_"," "))}</strong>: ${html(d.reason)}<br><small>${html(d.created_at)} · ${html(d.actor_id)} · Record ${html(d.id)}</small></p>`).join("")||"<p>No decisions recorded.</p>"}<h3>Evidence and assessment history</h3>${r.history.map(h=>`<section><h4>${html(data.activities.find(a=>a.id===h.snapshot.activity_id)?.title||h.snapshot.activity_id)} · ${html(h.action)}</h4><small>${html(h.created_at)} · ${html(h.actor_id)} · Record ${html(h.id)}</small><pre>${html(h.snapshot.answer)}</pre>${h.snapshot.feedback?`<p>Feedback: ${html(h.snapshot.feedback)}</p>`:""}${h.snapshot.scores?`<p>Criterion scores: ${html(JSON.stringify(h.snapshot.scores))}</p>`:""}${r.files.filter(f=>f.attempt_id===h.id).map(f=>`<p>Attachment: ${html(f.name)} · ${f.bytes} bytes<br><small>SHA-256 ${html(f.sha256)} · File ${html(f.id)}</small></p>`).join("")}</section>`).join("")}</article>`;
  }).join("")}</body></html>`;
  return new Response(body,{headers:{"Content-Type":"text/html; charset=utf-8","Cache-Control":"private, no-store","X-Content-Type-Options":"nosniff","Content-Security-Policy":"default-src 'none'; style-src 'unsafe-inline'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'"}});
 }catch(error){return learningErrorResponse(error);}
}
