/** Verified parts of Experrt's own product, not separate client engagements. */
export const caseStudies = [
  {
    slug: 'experrt-agentic-learning-platform',
    title: 'Connecting the learning journey in Experrt',
    category: 'Product engineering',
    summary: 'Bringing course creation, live delivery, learner activity and records into one learning platform.',
    problem: 'A training journey crosses many surfaces: the course outline, scheduled sessions, materials, learner work and the final record. When those are separate, trainers and learners have to reconstruct what happens next.',
    approach: 'We built the Experrt platform around connected learning records and dedicated views for course preparation, cohort delivery and learning. The work combines product design, application engineering and permission-aware access to shared records.',
    delivered: ['Course preparation and programme management', 'Cohort sessions, attendance and learner participation', 'Learning materials, discussions and submitted work', 'Assessment, grades and certificate workflows'],
    outcome: 'The implementation brings these workflows into the same product. A trainer can prepare learning and manage its delivery, while the learner has a place to access the course and participate. This is an evolving in-house product, with further work on role coverage and enterprise operations continuing.',
    lesson: 'Start with the whole service journey. A feature only becomes useful when the user can understand how it connects to their next action.',
    guide: 'digital-product-discovery-before-development',
  },
  {
    slug: 'experrt-learning-agent-reliability',
    title: 'Giving a learning agent dependable records',
    category: 'AI systems implementation',
    summary: 'Connecting AI-assisted learning preparation to persisted outcomes, workspace permissions and credit settlement.',
    problem: 'An AI response is not enough for operational work. The application needs to know whether an action completed, where its output lives and what happens when execution is interrupted.',
    approach: 'In Experrt, we introduced explicit agent execution records and coordinated saving of completed output with credit settlement. The implementation also includes recovery handling and workspace checks around access to results.',
    delivered: ['Recorded agent runs and persisted completed outputs', 'Credit reservations and settlement tied to execution', 'Recovery handling for interrupted or abandoned work', 'Workspace access checks around agent-related records'],
    outcome: 'The product has a concrete record of completed agent output and its associated credit settlement. This supports inspection and recovery rather than relying on conversational claims. It does not mean every possible agent action is automated or that every failure mode has been eliminated.',
    lesson: 'Design the execution lifecycle alongside the AI interaction. Permissions, interruptions and saved results are part of the user experience.',
    guide: 'how-to-scope-an-ai-agent-implementation',
  },
  {
    slug: 'experrt-training-records-and-resource-access',
    title: 'Connecting learning resources to accountable access',
    category: 'Workflow and systems integration',
    summary: 'Building permission-aware resource downloads, assessment operations and learning records inside Experrt.',
    problem: 'Learning operations involve materials, assessments and reports. Access must follow workspace membership, including when a person’s access changes after a record or download link was created.',
    approach: 'We connected resource downloads to a server-side access gateway and added membership checks to assessment and reporting operations. Selected assessment commands were moved into atomic database operations to keep related changes together.',
    delivered: ['Private resource storage with guarded downloads', 'Membership checks for assessment and reporting operations', 'Atomic assessment creation and deletion commands', 'Staff learning records and PDF reporting workflows'],
    outcome: 'These implemented controls tie resource and record access to the learning workspace. They provide a foundation for continued role-by-role verification. They are not a claim of external certification or a completed enterprise security programme.',
    lesson: 'The systems of record and the access model need to be designed together. A polished screen cannot substitute for checks at the point where data is read or changed.',
    guide: 'ai-pilot-to-production-checklist',
  },
] as const;
