/**
 * Published catalogue slugs seeded in migrations 020, 024 and 033.
 *
 * The sitemap uses these when Supabase is unreachable so a missing database
 * cannot 500 the crawl file. Live fetches still win when they return rows.
 */
export const FALLBACK_PUBLISHED_COURSE_SLUGS = [
  "ai-for-everyday-hr",
  "people-operations-workflow-automation",
  "digital-onboarding-and-employee-journeys",
  "hr-data-quality-and-connected-records",
  "ai-assisted-recruitment-operations",
  "hr-knowledge-and-employee-self-service",
  "people-analytics-for-hr-decisions",
  "employee-listening-with-ai",
  "hris-selection-and-integration",
  "skills-mapping-and-workforce-planning",
  "learning-operations-and-ai-enabled-development",
  "redesigning-hr-services-with-agents",
  "hr-transformation-strategy-and-roadmap",
  "responsible-ai-governance-for-hr",
  "leading-people-change-in-an-ai-workplace",
  "hr-technology-investment-and-value",

  "ai-foundations-for-every-role",
  "prompting-and-output-verification",
  "embedding-ai-in-daily-workflows",
  "ai-tooling-and-integration-clinic",
  "responsible-ai-use-at-work",
  "leading-an-ai-ready-team",
  "ai-governance-and-oversight-for-managers",
  "ai-strategy-and-oversight-for-executives",
  "ai-in-the-executive-workflow",
  "sponsoring-an-ai-literacy-programme",
  "getting-value-from-tools-you-already-own",
  "automating-the-work-nobody-wants",
  "data-you-can-actually-use",
  "choosing-technology-well",
  "running-a-rollout-that-sticks",
  "technology-for-non-technical-leaders",
  "robotics-what-it-can-and-cannot-do",
  "working-alongside-a-cobot",
  "running-and-troubleshooting-a-robotic-cell",
  "warehouse-and-logistics-automation-in-practice",
  "specifying-a-robotics-deployment",
  "safety-risk-and-compliance-for-robotic-workcells",
  "robotics-investment-and-operating-model",
  "writing-and-communicating-with-ai",
  "ai-for-customer-facing-teams",
  "ai-for-analysis-and-reporting",
  "building-ai-assistants-for-your-team",
  "running-an-ai-champions-network",
  "measuring-ai-adoption-and-value",
  "everyday-security-for-busy-teams",
  "from-spreadsheets-to-systems",
  "digital-change-without-the-theatre",
  "preparing-your-team-for-automation",
  "vision-systems-and-automated-inspection",
] as const;

export const COURSE_TITLES: Record<string, string> = {
  "ai-foundations-for-every-role": "AI Foundations for Every Role",
  "prompting-and-output-verification": "Prompting and Output Verification",
  "embedding-ai-in-daily-workflows": "Embedding AI in Daily Workflows",
  "ai-tooling-and-integration-clinic": "AI Tooling and Integration Clinic",
  "responsible-ai-use-at-work": "Responsible AI Use at Work",
  "leading-an-ai-ready-team": "Leading an AI-Ready Team",
  "ai-governance-and-oversight-for-managers":
    "AI Governance and Oversight for Managers",
  "ai-strategy-and-oversight-for-executives":
    "AI Strategy and Oversight for Executives",
  "ai-in-the-executive-workflow": "AI in the Executive Workflow",
  "sponsoring-an-ai-literacy-programme": "Sponsoring an AI Literacy Programme",
  "getting-value-from-tools-you-already-own":
    "Getting Value From the Tools You Already Own",
  "automating-the-work-nobody-wants": "Automating the Work Nobody Wants",
  "data-you-can-actually-use": "Data You Can Actually Use",
  "choosing-technology-well": "Choosing Technology Well",
  "running-a-rollout-that-sticks": "Running a Rollout That Sticks",
  "technology-for-non-technical-leaders":
    "Technology for Non-Technical Leaders",
  "robotics-what-it-can-and-cannot-do": "Robotics: What It Can and Cannot Do",
  "working-alongside-a-cobot": "Working Alongside a Cobot",
  "running-and-troubleshooting-a-robotic-cell":
    "Running and Troubleshooting a Robotic Cell",
  "warehouse-and-logistics-automation-in-practice":
    "Warehouse and Logistics Automation in Practice",
  "specifying-a-robotics-deployment": "Specifying a Robotics Deployment",
  "safety-risk-and-compliance-for-robotic-workcells":
    "Safety, Risk and Compliance for Robotic Workcells",
  "robotics-investment-and-operating-model":
    "Robotics Investment and the Operating Model",
  "writing-and-communicating-with-ai": "Writing and Communicating With AI",
  "ai-for-customer-facing-teams": "AI for Customer-Facing Teams",
  "ai-for-analysis-and-reporting": "AI for Analysis and Reporting",
  "building-ai-assistants-for-your-team":
    "Building AI Assistants for Your Team",
  "running-an-ai-champions-network": "Running an AI Champions Network",
  "measuring-ai-adoption-and-value": "Measuring AI Adoption and Value",
  "everyday-security-for-busy-teams": "Everyday Security for Busy Teams",
  "from-spreadsheets-to-systems": "From Spreadsheets to Systems",
  "digital-change-without-the-theatre": "Digital Change Without the Theatre",
  "preparing-your-team-for-automation": "Preparing Your Team for Automation",
  "vision-systems-and-automated-inspection":
    "Vision Systems and Automated Inspection",
  "ai-for-everyday-hr": "AI for Everyday HR",
  "people-operations-workflow-automation": "People Operations Workflow Automation",
  "digital-onboarding-and-employee-journeys": "Digital Onboarding & Employee Journeys",
  "hr-data-quality-and-connected-records": "HR Data Quality & Connected Records",
  "ai-assisted-recruitment-operations": "AI-Assisted Recruitment Operations",
  "hr-knowledge-and-employee-self-service": "HR Knowledge & Employee Self-Service",
  "people-analytics-for-hr-decisions": "People Analytics for Better HR Decisions",
  "employee-listening-with-ai": "Employee Listening with AI",
  "hris-selection-and-integration": "HRIS Selection & Connected People Systems",
  "skills-mapping-and-workforce-planning": "Skills Mapping & Technology-Enabled Workforce Planning",
  "learning-operations-and-ai-enabled-development": "Learning Operations & AI-Enabled Development",
  "redesigning-hr-services-with-agents": "Redesigning HR Services with AI Agents",
  "hr-transformation-strategy-and-roadmap": "HR Transformation Strategy & Roadmap",
  "responsible-ai-governance-for-hr": "Responsible AI Governance for HR Leaders",
  "leading-people-change-in-an-ai-workplace": "Leading People Change in an AI Workplace",
  "hr-technology-investment-and-value": "HR Technology Investment & Value",
};
