"use client";
import { useEffect, useRef, useState } from "react";
import { Lightbulb, Volume2, VolumeX, Sparkles, X } from "lucide-react";
import { Pip } from "../art";
import { coachLines, coachPhase } from "@/lib/wonderlab/adventure/coaching";
import type {
  Adventure,
  AdventureState,
} from "@/lib/wonderlab/adventure/types";

export function AdventureCoach({
  game,
  state,
  revision,
  aiEnabled,
  allowance,
  busy,
  narrate,
  stop,
}: {
  game: Adventure;
  state: AdventureState;
  revision: number;
  aiEnabled: boolean;
  allowance: number;
  busy: boolean;
  narrate: (text: string) => void;
  stop: () => void;
}) {
  const level = game.levels[state.round];
  const round = state.rounds[state.round];
  const lines = coachLines[level.kind];
  const phase = coachPhase(level, round);
  const [detail, setDetail] = useState<{
    revision: number;
    kind: "hint" | "why";
  } | null>(null);
  const [response, setResponse] = useState<{
    revision: number;
    text: string;
  } | null>(null);
  const [remaining, setRemaining] = useState(allowance);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const pending = useRef(false);
  const controller = useRef<AbortController | null>(null);
  useEffect(() => () => controller.current?.abort(), []);
  const text =
    detail?.revision === revision ? lines[detail.kind] : lines[phase];
  async function ask() {
    if (pending.current || busy || !aiEnabled || remaining <= 0) return;
    pending.current = true;
    setLoading(true);
    setError("");
    const request = new AbortController();
    controller.current = request;
    try {
      const res = await fetch("/api/wonderlab/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        signal: request.signal,
        body: JSON.stringify({
          slug: game.slug,
          variant: "coach-hint",
          revision,
          requestId: crypto.randomUUID(),
        }),
      });
      const result = await res.json();
      if (!res.ok)
        throw new Error(
          result.error ??
            "The AI hint is unavailable. Pip's practice hint is still here.",
        );
      setResponse({ revision, text: result.text });
      setRemaining((n) => Math.max(0, n - 1));
    } catch (err) {
      if (!request.signal.aborted)
        setError(
          err instanceof Error
            ? err.message
            : "Use Pip's practice hint and keep playing.",
        );
    } finally {
      if (!request.signal.aborted) {
        pending.current = false;
        setLoading(false);
      }
    }
  }
  return (
    <aside className="wd-companion" aria-label="Pip's learning guidance">
      <div className="wd-companion-avatar">
        <Pip small />
        <span>PIP</span>
      </div>
      <div className="wd-companion-body">
        <div className="wd-companion-heading">
          <strong>
            {round.solved
              ? "Let's look at what worked."
              : "I'm here to help you test your ideas."}
          </strong>
          <span>Fictional guide · prepared guidance</span>
        </div>
        <p aria-live="polite">{text}</p>
        <div className="wd-companion-actions">
          <button onClick={() => setDetail({ revision, kind: "hint" })}>
            <Lightbulb size={15} /> Give me a hint
          </button>
          <button onClick={() => setDetail({ revision, kind: "why" })}>
            How does this help me use AI?
          </button>
          <button
            onClick={() => narrate(text)}
            aria-label="Hear Pip's guidance"
          >
            <Volume2 size={15} /> Listen
          </button>
          <button onClick={stop} aria-label="Stop Pip’s voice">
            <VolumeX size={15} />
          </button>
          {aiEnabled && (
            <button disabled={busy || loading || remaining <= 0} onClick={ask}>
              <Sparkles size={15} />
              {loading ? "Thinking about your game…" : "Ask AI about this step"}
            </button>
          )}
        </div>
        {aiEnabled && (
          <small>
            {remaining > 0
              ? `${remaining} guided AI responses remain. Asking for an AI hint uses one response.`
              : "You have used your guided AI responses. Pip's prepared hints are still available."}
          </small>
        )}
        {response?.revision === revision && (
          <div className="wd-coach-response">
            <strong>
              This hint was generated by AI. Check it against your game.
            </strong>
            <button
              aria-label="Close the AI hint"
              onClick={() => setResponse(null)}
            >
              <X size={16} />
            </button>
            <p>{response.text}</p>
          </div>
        )}
        {error && (
          <p role="status">{error} You can keep using the prepared hints.</p>
        )}
      </div>
    </aside>
  );
}
