"use client";
import {useCallback,useEffect,useState} from "react";
import type {DeliveryCommand} from "@/lib/lms/delivery-schema";
export type DeliveryLiveData={groups:{id:string;title:string;status:string;sessions:{id:string;title:string;starts_at:string;ends_at:string;join_url:string|null;register:{enrolment_id:string;assignment_id:string;name:string;status:"present"|"late"|"absent"|"excused"|null;recorded_at:string|null}[]}[]}[]};
export function DeliveryLive({programmeId,canManage,send}:{programmeId:string;canManage:boolean;send:(c:DeliveryCommand)=>Promise<boolean>}){
 const [data,setData]=useState<DeliveryLiveData|null>(null),[error,setError]=useState("");
 const load=useCallback(async()=>{try{const r=await fetch(`/api/lms/programmes/${programmeId}/workspace?view=live`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw Error(d.error);setData(d);setError("");}catch(e){setError(e instanceof Error?e.message:"Could not load live sessions");}},[programmeId]);
 useEffect(()=>{void load();},[load]);
 return <section className="lms-panel"><h2>Live training and attendance</h2><p role="status">{error||(!data?"Loading the schedule…":"")}</p>{error&&<button className="lms-button" onClick={load}>Retry</button>}{data&&!data.groups.length&&<p className="my-5">No teaching sessions are scheduled yet. Your programme team can set them up here.</p>}{data?.groups.map(g=><article key={g.id} className="my-5 rounded-xl border p-5"><h3>{g.title}</h3>{g.sessions.map(s=><details key={s.id} className="my-4 rounded-xl bg-muted/30 p-4"><summary className="cursor-pointer font-semibold">{s.title} · {new Date(s.starts_at).toLocaleString()}</summary>{s.join_url&&<a className="my-4 inline-block text-brand underline" href={s.join_url} target="_blank" rel="noopener noreferrer">Join session</a>}<p className="my-3 text-xs text-muted-foreground">Times use your browser’s timezone. Attendance can be recorded after a session starts. Unrecorded attendance is not counted as absence.</p>{s.register.map(r=><div key={r.enrolment_id} className="my-3 flex flex-wrap items-center justify-between gap-4"><span>{r.name}</span>{canManage?<label className="lms-form"><span className="sr-only">Attendance for {r.name}</span><select disabled={g.status==="cancelled"||new Date(s.starts_at)>new Date()} value={r.status||""} onChange={async e=>{if(await send({action:"attendance.save",session_id:s.id,enrolment_id:r.enrolment_id,status:e.target.value as "present"|"late"|"absent"|"excused",expected_status:r.status}))await load();}}><option value="" disabled>Not recorded</option>{["present","late","absent","excused"].map(v=><option key={v} value={v}>{v}</option>)}</select></label>:<span>{r.status||"Not recorded"}</span>}</div>)}</details>)}{canManage&&["scheduled","running"].includes(g.status)&&<details className="mt-5 border-t pt-4"><summary className="cursor-pointer text-sm font-semibold text-brand">Add a teaching session</summary><form className="lms-form mt-5 space-y-4" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);const starts=new Date(String(f.get("start"))),ends=new Date(String(f.get("end")));if(ends<=starts){setError("The session must end after it starts.");return;}if(await send({action:"session.create",cohort_id:g.id,title:String(f.get("title")),starts_at:starts.toISOString(),ends_at:ends.toISOString(),join_url:String(f.get("join")||"")})){form.reset();await load();}}}><label>Title<input name="title" required minLength={3}/></label><div className="grid gap-4 sm:grid-cols-2"><label>Starts (your local time)<input name="start" type="datetime-local" required/></label><label>Ends (your local time)<input name="end" type="datetime-local" required/></label></div><label>Meeting link<input name="join" type="url" placeholder="https://…"/></label><button className="lms-button">Add session</button></form></details>}</article>)}</section>;
}
