"use client";
import {useCallback,useEffect,useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {useLearningOverview,lmsCommand} from "@/lib/lms/client";
export function ProgrammeIndex(){
 const overview=useLearningOverview(),router=useRouter();
 const [rows,setRows]=useState<{id:string;title:string;status:string;invitation:string|null}[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[create,setCreate]=useState(false),[filter,setFilter]=useState("active");
 const load=useCallback(async()=>{try{const r=await fetch("/api/lms/delivery",{cache:"no-store"});const d=await r.json();if(!r.ok)throw Error(d.error);setRows(d);setError("");}catch(e){setError(e instanceof Error?e.message:"Could not load programmes");}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]);
 return <div className="lms-workspace programme-directory py-8"><header className="mb-8 flex flex-wrap items-start justify-between gap-5"><div><p className="lms-eyebrow">Your learning and teaching</p><h1 className="my-3">Programmes</h1><p className="max-w-2xl text-muted-foreground">Open a programme to continue. Its learning, people, sessions and feedback stay together.</p></div>{overview.data?.can_manage&&<div className="flex gap-3"><button className="lms-button secondary" onClick={()=>setCreate(!create)}>{create?"Close":"Use existing courses"}</button><Link className="lms-button" href="/dashboard/programmes/new">Build a programme</Link></div>}</header><p role="status">{loading?"Loading programmes…":error}</p>{error&&<button className="lms-button" onClick={load}>Retry</button>}
 {create&&overview.data&&<form className="lms-panel lms-form mb-6" onSubmit={async e=>{e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{const p=await lmsCommand<{id:string}>({action:"programme.create",payload:{title:String(f.get("title")),goal:String(f.get("goal")),client_org_id:String(f.get("client"))||null,version_ids:f.getAll("version").map(String),due_at:null}});router.push(`/dashboard/programmes/${p.id}`);}catch(err){setError(err instanceof Error?err.message:"Could not create programme");}finally{setBusy(false);}}}><h2>Start with the programme</h2><label>Name<input name="title" required minLength={3} placeholder="Banking analytics development programme"/></label><label>What should people be able to do?<textarea name="goal" required minLength={3}/></label><label>Who is this for?<select name="client"><option value="">Our own people</option>{overview.data.clients.filter(c=>c.provider_org_id===overview.data?.org_id&&c.state==="accepted").map(c=><option key={c.id} value={c.client_org_id}>{c.client_name}</option>)}</select></label><p className="text-sm">Choose content from your library. You will prepare delivery and add learners inside the programme.</p>{overview.data.versions.filter(v=>!overview.data?.versions.some(other=>other.course_id===v.course_id&&other.version>v.version)).map(v=><label key={v.id} className="lms-check"><input name="version" type="checkbox" value={v.id}/>{v.title}</label>)}{!overview.data.versions.length&&<p>Publish content in your <Link className="text-brand underline" href="/dashboard/studio">content library</Link> before creating a programme.</p>}<button className="lms-button" disabled={busy||!overview.data.versions.length}>Create programme</button></form>}
 <div className="my-6 flex gap-3">{["active","archived"].map(v=><button key={v} aria-pressed={filter===v} onClick={()=>setFilter(v)} className={`rounded-full border px-4 py-2 text-sm ${filter===v?"bg-foreground text-background":""}`}>{v==="active"?"Current programmes":"Archived programmes"}</button>)}</div>
 <div className="grid gap-5 lg:grid-cols-2">{rows.filter(p=>p.status===filter).map(p=><article key={p.id} className="lms-panel programme-list-card"><span className="lms-badge">{p.invitation==="pending"?"Invitation to join":p.status==="archived"?"Archived":"In your workspace"}</span><h2 className="my-4">{p.title}</h2><p className="mb-5 text-sm text-muted-foreground">Learning, sessions, assessment and progress in one place.</p>{p.invitation==="pending"?<button disabled={busy} className="lms-button" onClick={async()=>{setBusy(true);try{const r=await fetch(`/api/lms/programmes/${p.id}/workspace`,{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({action:"staff.accept"})});const d=await r.json();if(!r.ok)throw Error(d.error);await load();}catch(e){setError(e instanceof Error?e.message:"Could not accept invitation");}finally{setBusy(false);}}}>Accept invitation</button>:<Link className="lms-button" href={`/dashboard/programmes/${p.id}`}>Open programme</Link>}</article>)}</div>{!loading&&!error&&!rows.filter(p=>p.status===filter).length&&<div className="lms-panel"><h2>{filter==="active"?"Your programmes will appear here":"No archived programmes"}</h2><p>{overview.data?.can_manage?"Create a programme to bring your content, learners and teaching together.":"When you are assigned learning or invited to teach, open it here to get started."}</p></div>}
 </div>;
}
