"use client";
import {useCallback,useEffect,useState} from "react";
import Link from "next/link";
import {ScheduleDelivery} from "./schedule-delivery";
type Delivery = {can_manage:boolean; changed:number; available:{id:string;title:string}[]; cohorts:{id:string;title:string;status:string;timezone:string;location:string|null;enrolled:boolean;sessions:{id:string;title:string;starts_at:string;ends_at:string}[]}[]};
export function ProgrammeDelivery({programmeId,embedded=false,onChanged}:{programmeId:string;embedded?:boolean;onChanged?:()=>void}) {
 const [data,setData]=useState<Delivery|null>(null),[error,setError]=useState(""),[selected,setSelected]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const [courses,setCourses]=useState<{id:string;title:string}[]>([]),[creating,setCreating]=useState(false);
 const load=useCallback(async()=>{try{const r=await fetch(`/api/lms/programmes/${programmeId}/delivery`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw Error(d.error);setData(d);setError("");}catch(e){setError(e instanceof Error?e.message:"Could not load sessions");}},[programmeId]);
 useEffect(()=>{void load();},[load]);
 async function act(action:"link"|"enrol",cohort_id:string){if(busy)return;setBusy(true);setMessage("");try{const r=await fetch(`/api/lms/programmes/${programmeId}/delivery`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,cohort_id})});const d=await r.json();if(!r.ok)throw Error(d.error);setData(d);setSelected("");setError("");setMessage(action==="link"?"Live group connected. Confirm learner places when you are ready.":`${d.changed} learner places confirmed.`);onChanged?.();}catch(e){setError(e instanceof Error?e.message:"Could not update delivery");}finally{setBusy(false);}}
 return <section className="lms-panel" id="live-delivery"><div className="lms-row between"><div><span className="lms-eyebrow">Part of your programme</span><h2>Live sessions</h2><p className="text-sm text-muted-foreground">Your workshops and scheduled training, alongside your course activities.</p></div>{data?.can_manage&&!embedded&&<Link href="/dashboard/cohorts/new" className="lms-button secondary">Schedule a group →</Link>}</div>
 {embedded&&data?.can_manage&&<div className="my-4"><button className="lms-button secondary" onClick={async()=>{if(creating){setCreating(false);return;}try{const r=await fetch(`/api/lms/programmes/${programmeId}/live-setup`);const d=await r.json();if(!r.ok)throw Error(d.error);setCourses(d.courses);setCreating(true);}catch(e){setError(e instanceof Error?e.message:"Could not open teaching setup");}}}>{creating?"Close group setup":"Create a teaching group"}</button>{creating&&<ScheduleDelivery courses={courses} programmeId={programmeId} onCreated={()=>{setCreating(false);void load();onChanged?.();}}/>}</div>}
 {error&&<p role="alert" className="my-3 text-sm text-destructive">{error} <button onClick={load}>Retry</button></p>}{message&&<p role="status" className="lms-notice">{message}</p>}
 {data?.can_manage&&<div className="my-5 rounded-xl border p-4"><label htmlFor={`link-${programmeId}`} className="block text-sm font-semibold">Connect an existing live group</label><p className="my-2 text-xs text-muted-foreground">Choose a group that delivers this programme. Linking keeps existing course content, grades and completion rules intact. Enrolment is a separate step.</p><div className="flex flex-wrap gap-2"><select id={`link-${programmeId}`} value={selected} onChange={e=>setSelected(e.target.value)} className="min-w-0 flex-1 rounded-xl border bg-card p-3 text-sm"><option value="">Choose a live group</option>{data.available.map(c=><option value={c.id} key={c.id}>{c.title}</option>)}</select><button className="lms-button" disabled={!selected||busy} onClick={()=>act("link",selected)}>Connect group</button></div></div>}
 {!data&&!error&&<p className="mt-5 text-sm">Loading live sessions…</p>}
 {data&&!data.cohorts.length&&<p className="mt-5 rounded-xl bg-muted/40 p-5 text-sm text-muted-foreground">No live sessions are connected to this programme yet. Your course activities remain available in Learn & practise.</p>}
 <div className="mt-5 space-y-4">{data?.cohorts.map(c=><article key={c.id} className="rounded-2xl border p-5"><div className="lms-row between"><h3 className="text-lg font-semibold">{c.title}</h3><span className="lms-badge">{c.status}</span></div><p className="my-2 text-xs text-muted-foreground">{c.location||"Location to be confirmed"} · {c.timezone}</p><ul className="my-4 space-y-3">{c.sessions.map(s=><li key={s.id} className="rounded-xl bg-muted/30 p-3"><strong className="block text-sm">{s.title}</strong><span className="text-xs text-muted-foreground">{new Date(s.starts_at).toLocaleString(undefined,{dateStyle:"medium",timeStyle:"short",timeZone:c.timezone})}</span></li>)}</ul>{!c.sessions.length&&<p className="my-3 text-sm text-muted-foreground">The trainer has not added session dates yet.</p>}<div className="flex flex-wrap gap-2">{!embedded&&(c.enrolled||data.can_manage)&&<Link className="lms-button secondary" href={`/dashboard/cohorts/${c.id}`}>Open live group & wall →</Link>}{data.can_manage&&["scheduled","running"].includes(c.status)&&<button className="lms-button" disabled={busy} onClick={()=>act("enrol",c.id)}>{busy?"Updating…":"Confirm learner places"}</button>}</div>{!c.enrolled&&!data.can_manage&&<p className="mt-3 text-sm text-muted-foreground">Your programme is assigned. Your trainer still needs to confirm your place in this live group.</p>}</article>)}</div>
 </section>;
}
