"use client";
import {useState} from "react";
import {useLearningOverview,lmsCommand} from "@/lib/lms/client";
import type {DeliveryWorkspace} from "@/lib/lms/delivery-schema";
export function ProgrammePeople({data,refresh}:{data:DeliveryWorkspace;refresh:()=>Promise<void>}) {
 const overview=useLearningOverview();const [selected,setSelected]=useState<string[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const audience=data.programme.client_org_id||overview.data?.org_id;
 const members=overview.data?.members.filter(m=>m.org_id===audience&&!data.records.some(r=>r.user_id===m.id))||[];
 return <section className="lms-panel"><h2>People on this programme</h2><p className="my-3 text-sm text-muted-foreground">Assign learners once. Their lessons, practical work, live sessions and feedback belong to this programme.</p><p role="status">{message||overview.error}</p><div className="my-4 divide-y">{data.records.map(r=><div key={r.id} className="flex justify-between py-3"><strong>{r.name}</strong><span>{r.completed_at?"Coursework complete":"Assigned"}</span></div>)}</div>{["manager","client"].includes(data.role)&&<details className="rounded-xl border p-4" open={!data.records.length}><summary className="cursor-pointer font-semibold">Add learners</summary><div className="lms-form my-4 max-h-64 space-y-3 overflow-auto">{members.map(m=><label key={m.id} className="lms-check"><input type="checkbox" checked={selected.includes(m.id)} onChange={e=>setSelected(p=>e.target.checked?[...p,m.id]:p.filter(id=>id!==m.id))}/>{m.name}</label>)}</div>{!members.length&&<p className="my-4 text-sm">All available members are assigned. Add new people to the audience organisation to include them here.</p>}<button className="lms-button" disabled={busy||!selected.length} onClick={async()=>{setBusy(true);try{await lmsCommand({action:"programme.assign",payload:{id:data.programme.id,user_ids:selected}});setSelected([]);setMessage("Learners added to the programme.");await refresh();}catch(e){setMessage(e instanceof Error?e.message:"Could not assign learners");}finally{setBusy(false);}}}>Add {selected.length||"selected"} learners</button></details>}</section>;
}
