export type Decision = {
  text: string;
  choices: { text: string; feedback: string; best: boolean }[];
};
const patterns: Record<
  string,
  [string, string, string, string, string, string]
> = {
  scope: [
    "Choose a regular task where you can check and correct a draft.",
    "This gives you a small task to try before using the agent more widely. Write down how you do it today so you can compare the time and results later.",
    "Ask the agent to take over all the work and decide what success means afterwards.",
    "The agent would have to guess what you want and which decisions it may make. Choose one smaller task and describe a correct result before trying it.",
    "Choose the task with the biggest possible saving, even if you do not have the information it needs.",
    "A possible saving does not make the task ready to try. First check that you have the information and can tell whether the result is right.",
  ],
  brief: [
    "Say which information to use, what to produce, how to check it and when to ask for help.",
    "These instructions explain the task clearly. Try an ordinary example and one with missing information to check that the agent knows what to do.",
    "Ask the agent to make the result more professional without explaining what is missing.",
    "A more professional tone will not add a requirement the agent does not know about. Explain what the result should include and how you will check it.",
    "Let the agent guess what you need from earlier conversations.",
    "Earlier conversations may be incomplete or out of date. Put the important rules in the current written instructions.",
  ],
  access: [
    "Demonstrate the capability in the intended account and record conditions needed for the task to run.",
    "A documented feature and working account access are different evidence. Record what you actually tested and label any remaining assumption.",
    "Treat the provider’s example as proof that this account can run the workflow.",
    "The example does not establish your plan, region or integration access. Perform a harmless account-level test first.",
    "Give the agent broader access until the task appears to work.",
    "Broad access obscures the actual requirement and expands consequences. Test the smallest necessary capability in a practice area.",
  ],
  authority: [
    "Prepare the draft and request approval for the specific action that affects other people or records.",
    "The instruction permits preparation but reserves the external effect for approval. Show the current content, destination and action to the owner.",
    "Proceed because the connected application technically permits the action.",
    "Technical access is not authorisation. Enforce the agreed rule about what the agent may do and check that no external effect occurred.",
    "Treat an earlier approval for another draft as permission for this action.",
    "Approval belongs to particular content and circumstances. A new destination or revision needs a fresh decision under the stated policy.",
  ],
  injection: [
    "Keep the owner’s rules and treat the request in the file as something to report, not permission to act.",
    "The file gives the agent information, but cannot change what the owner has allowed it to do. Explain the conflicting request and do only the agreed task.",
    "Follow the request because it is written in the file the agent was told to use.",
    "Permission to read a file does not mean permission to do everything it asks. Keep the owner’s rules in place and ask them about the conflict.",
    "Ignore the whole file without telling anyone.",
    "This could leave important information out of the result. Explain the conflict and whether the remaining information is enough to finish the task.",
  ],
  context: [
    "Apply the current explicit constraint and verify a subsequent result.",
    "The current instruction wins over an old preference. Inspect the next result rather than relying only on an acknowledgement.",
    "Keep the remembered preference because it has been used before.",
    "Past use does not make the preference current. Compare it with the dated instruction and correct the context.",
    "Delete all useful context and start without checking the conflict.",
    "Removing everything can lose necessary constraints. Identify the outdated item, correct it and check the effect.",
  ],
  sources: [
    "Check the original record, its scope and the date the event takes effect.",
    "This establishes what the source supports and when it applies. State any inference separately from the verified fact.",
    "Use the newest article without checking its original source.",
    "A new article can repeat old or unsupported information. Inspect the underlying evidence and its event date.",
    "Treat several repeats of the same announcement as separate confirmation.",
    "Repeated reporting shares the same evidential origin. Record that dependence rather than inflating confidence.",
  ],
  missing: [
    "Report the missing value or unavailable source as a separate exception.",
    "Missing is not zero or a known status. Preserve the gap so that the owner can resolve it without being misled.",
    "Fill the gap with the most likely value so the report remains complete.",
    "The inferred value would appear to be a fact. Keep the gap explicit unless the brief authorises and labels an estimate.",
    "Remove the affected record from the report without explanation.",
    "Omitting the record hides incomplete coverage. Keep its ID in the exception list and state what could not be checked.",
  ],
  schedule: [
    "Confirm source availability and execution mode, then test one manual and one scheduled run.",
    "A schedule alone does not prove the workflow can reach the data. Record the conditions needed for the task to run and inspect actual outputs.",
    "Enable the most frequent schedule to maximise activity.",
    "More runs can add cost and duplicates without helping a decision. Match the trigger to input freshness and the owner’s needs.",
    "Assume a cloud task can read any local file used in an earlier session.",
    "Local and remote access are separate. Check the documented execution mode and where the scheduled task obtains its files.",
  ],
  overdue: [
    "Classify P101 as overdue and keep P103 in a separate missing-date list.",
    "P101 is incomplete and its due date is earlier than the cut-off. P102 is complete; P103 has no date; P104 is due today, so it is not overdue under the supplied rule.",
    "Include P101, P102 and P104 because their dates are on or before the reporting date.",
    "This ignores completion status and the strict earlier-than rule. Check each classification with the tracker definition.",
    "Mark P103 overdue because the absent date suggests it was forgotten.",
    "An absent date does not establish a missed deadline. Report the missing date separately and ask its owner to resolve it.",
  ],
  retry: [
    "Check what has already happened and continue only the unfinished steps.",
    "The agent may have saved a draft before the connection failed. Look for that result and check the task reference before trying again, so you do not repeat completed work.",
    "Start the whole task again because it is marked as failed.",
    "The failure may have happened after some steps were completed. Starting again without checking could create a second report or repeat another action.",
    "Delete the existing result to make it easier to start again.",
    "The result may contain useful work and help explain what went wrong. Keep it and check what happened before deciding what needs to change.",
  ],
  test: [
    "Write expected outcomes and check normal, incomplete, boundary and failure cases.",
    "A varied set exposes distinct ways the workflow can fail. Keep expected results independent of the agent’s explanation.",
    "Accept a successful demonstration as evidence that every case is covered.",
    "One example does not test missing data, boundaries or interruption. Add cases with known outcomes.",
    "Change expected results to match the agent’s latest output.",
    "This removes the independent standard. Investigate the disagreement and change requirements only when the owner explicitly decides to do so.",
  ],
  value: [
    "Include preparation, review, correction, maintenance and operating charges.",
    "Value depends on the whole process at an equivalent quality standard. Separate one-off setup from time spent on the regular task.",
    "Compare only the agent’s execution time with all manual work.",
    "This excludes human work required to obtain an acceptable result and overstates the improvement.",
    "Convert all saved time into guaranteed cash savings.",
    "Time has value but does not automatically remove a cash cost. Label the assumed rate and explain whether any expenditure actually changes.",
  ],
  certificate: [
    "Have a reviewer check the work and provide anything still missing.",
    "The reviewer needs to check your skills in every required area. Finishing practice activities and producing a good-looking result are not enough to show that you have passed.",
    "Award a certificate because every practice activity is marked complete.",
    "Practice progress shows which activities you have worked through. A certificate needs a pass in the practical assessment.",
    "Use high scores in other areas to make up for the failed permission check.",
    "You need at least 3 out of 4 in every area. If the permission check is below that score, improve that part and have it checked again.",
  ],
  routing: [
    "Record the request as awaiting approval and preserve its request ID.",
    "The access category requires the IT owner’s decision. A routing draft can prepare the decision without granting rights.",
    "Grant access because all required fields are present.",
    "Valid fields make the request complete, not authorised. Keep the access grant behind the defined approval step.",
    "Reject all access requests without showing them to the owner.",
    "The policy reserves a decision rather than prohibiting every request. Route it to the accountable owner with supporting information.",
  ],
  duplicate: [
    "Use the existing item ID or run key to check whether the intended output already exists.",
    "Matching the intended operation to its recorded effect prevents a repeated event from becoming new work.",
    "Create a new output because each trigger delivery deserves its own response.",
    "Delivery can be repeated for the same intended event. Distinguish deliveries from unique business work.",
    "Suppress every similar-looking future item.",
    "Similar items can be legitimate new work. Use stable identifiers and reporting periods rather than vague resemblance.",
  ],
  editorial: [
    "Correct the claims without supporting facts and have the exact revised draft reviewed.",
    "The approved fact pack establishes what can be claimed. Material corrections change the draft and require a review of that revision.",
    "Keep the stronger promise because it makes the message more persuasive.",
    "A persuasive claim still needs support. Remove invented qualifications, benefits or prices.",
    "Publish first and correct the facts if readers notice.",
    "This transfers fact-checking to readers and breaches the publishing boundary. Complete review before the external action.",
  ],
  rights: [
    "Use an asset with a recorded origin and established usage conditions, with useful alternative text.",
    "A usable image needs both an appropriate visual purpose and a defensible source record. Check it at the intended display size.",
    "Use the unidentified photo because it is publicly visible online.",
    "Public visibility does not establish permission to reuse. Confirm rights or choose a properly documented alternative.",
    "Omit every image to avoid maintaining an asset record.",
    "The course requires an accessible visual. Record the origin of an appropriate asset rather than removing the learning aid.",
  ],
  revision: [
    "Update all affected outputs, record the new version and obtain review of that version.",
    "A changed fact can affect several formats. Trace the change through the batch and tie approval to the current content.",
    "Reuse the old approval because the overall topic has not changed.",
    "The approval applied to earlier facts and content. The new version needs the review required by the workflow.",
    "Change only the first draft the reviewer is likely to read.",
    "Unchanged sibling outputs would remain inaccurate. Use the content inventory to identify every affected format.",
  ],
  code: [
    "Restore the behavioural requirement and use a test that fails on the original bug.",
    "A meaningful test detects the problem independently. Inspect assertions and implementation rather than accepting a green result alone.",
    "Accept the altered expected value because the test now passes.",
    "The change weakens the standard instead of fixing behaviour. Compare it with the issue’s checks for a correct result.",
    "Add a dependency before checking whether the small fix needs one.",
    "A dependency changes cost and maintenance scope. Establish the cause and prefer a justified small, focused fix.",
  ],
  isolation: [
    "Use a disposable checkout and record the initial state and credential boundaries.",
    "Isolation makes changes reviewable and recovery possible without disturbing unrelated work. Keep production secrets out of the lab.",
    "Run the task against the production checkout to make the results realistic.",
    "The practice task does not require production state. A disposable environment can demonstrate behaviour without affecting live work.",
    "Delete unrelated changes so the agent has a cleaner starting point.",
    "Those changes may belong to someone else. Preserve them and choose a separate practice workspace.",
  ],
  handoff: [
    "Reject the incomplete handoff, name the missing evidence and retain the accountable owner.",
    "The receiving role needs the agreed requirements for the information received. Record the rejection rather than silently guessing a source or authority.",
    "Fill the missing source with a plausible reference so work can continue.",
    "A plausible reference may not support the claim. Return the handoff with the specific gap.",
    "Allow the agents to approve each other’s expanded authority.",
    "Agreement between agents does not change the owner’s permissions. Keep the final decision with the assigned human owner.",
  ],
  loop: [
    "Stop at the revision limit and give the owner the conflicting evidence.",
    "A limit on revisions keeps costs under control and shows when a person needs to decide. Keep both views and the facts behind them.",
    "Continue exchanging drafts until every agent agrees.",
    "Repeated agreement-seeking can spend indefinitely without new evidence. Honour the revision limit.",
    "Choose the most confident agent without examining the sources.",
    "Confidence is not an evidential tie-breaker. Compare the underlying records and escalate unresolved judgement.",
  ],
  team: [
    "Compare both workflows on the same cases and quality standard before choosing.",
    "Coordination adds costs and may still produce claims without supporting facts. Use equivalent cases to assess whether the role split helps.",
    "Choose the larger team because specialised roles guarantee better quality.",
    "Role names do not establish independence or accuracy. Test the team against original sources.",
    "Choose whichever workflow finishes its automated steps first.",
    "Elapsed execution omits review and corrections. Compare the complete process and acceptance failures.",
  ],
};
export function decision(
  text: string,
  pattern: string,
  rotation = 0,
): Decision {
  const p = patterns[pattern];
  if (!p) throw new Error("Unknown decision pattern: " + pattern);
  const choices = [0, 2, 4].map((offset) => ({
    text: p[offset],
    feedback: p[offset + 1],
    best: offset === 0,
  }));
  return {
    text,
    choices: [
      ...choices.slice(rotation % 3),
      ...choices.slice(0, rotation % 3),
    ],
  };
}
