-- HR, AI and People Operations: 16 facilitated courses, each with three two-hour workshops.
-- Additive catalogue seed. Existing slugs and edited outlines are preserved.
ALTER TABLE public.courses DROP CONSTRAINT IF EXISTS courses_category_check;
ALTER TABLE public.courses ADD CONSTRAINT courses_category_check CHECK (category IN ('ai','technology','robotics','hr'));

INSERT INTO public.courses (slug,title,summary,category,level,duration_hours,delivery_modes,learning_outcomes,target_roles,status)
VALUES ('ai-for-everyday-hr','AI for Everyday HR','Use AI to draft, organise and improve everyday HR work while checking accuracy and keeping sensitive employee information protected.','hr','practitioner',6,ARRAY['in_person','virtual'],'["Create a prioritised HR task shortlist", "Produce a checked HR communication draft", "Leave with a reusable AI task playbook"]'::jsonb,ARRAY['individual_contributor','team_lead'],'published') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,1,'Choose useful HR tasks','Map repetitive work and separate drafting support from decisions that need a person.',2,'["Create a prioritised HR task shortlist"]'::jsonb FROM public.courses WHERE slug='ai-for-everyday-hr' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,2,'Write and verify a useful brief','Practise with fictional employee scenarios, source documents and a clear review checklist.',2,'["Produce a checked HR communication draft"]'::jsonb FROM public.courses WHERE slug='ai-for-everyday-hr' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,3,'Build your working playbook','Document approved inputs, review responsibilities and the point at which work stops for help.',2,'["Leave with a reusable AI task playbook"]'::jsonb FROM public.courses WHERE slug='ai-for-everyday-hr' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.courses (slug,title,summary,category,level,duration_hours,delivery_modes,learning_outcomes,target_roles,status)
VALUES ('people-operations-workflow-automation','People Operations Workflow Automation','Turn a repetitive people-service request into a clear workflow with ownership, approvals and a reliable handover when automation cannot help.','hr','practitioner',6,ARRAY['in_person','virtual'],'["Draw the current service workflow", "Build an automation specification", "Produce an exception-tested workflow checklist"]'::jsonb,ARRAY['individual_contributor','team_lead'],'published') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,1,'Find the friction','Map a fictional HR request from intake to resolution and identify duplicate handling.',2,'["Draw the current service workflow"]'::jsonb FROM public.courses WHERE slug='people-operations-workflow-automation' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,2,'Design the automated steps','Specify triggers, validation, routing and human approval without exposing personal records.',2,'["Build an automation specification"]'::jsonb FROM public.courses WHERE slug='people-operations-workflow-automation' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,3,'Test the exceptions','Walk through missing information, duplicate requests and failed handovers.',2,'["Produce an exception-tested workflow checklist"]'::jsonb FROM public.courses WHERE slug='people-operations-workflow-automation' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.courses (slug,title,summary,category,level,duration_hours,delivery_modes,learning_outcomes,target_roles,status)
VALUES ('digital-onboarding-and-employee-journeys','Digital Onboarding & Employee Journeys','Create an onboarding experience that connects HR, managers and IT, using technology to make responsibilities and the next step clear.','hr','practitioner',6,ARRAY['in_person','virtual'],'["Create an employee journey map", "Design a connected onboarding checklist", "Produce an onboarding improvement plan"]'::jsonb,ARRAY['individual_contributor','team_lead'],'published') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,1,'See the journey','Map the first 90 days from the employee perspective using a fictional starter scenario.',2,'["Create an employee journey map"]'::jsonb FROM public.courses WHERE slug='digital-onboarding-and-employee-journeys' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,2,'Connect the handovers','Define tasks, owners, dependencies and useful reminders across HR, managers and IT.',2,'["Design a connected onboarding checklist"]'::jsonb FROM public.courses WHERE slug='digital-onboarding-and-employee-journeys' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,3,'Improve the experience','Test accessibility, late starts and missed tasks, then choose feedback points.',2,'["Produce an onboarding improvement plan"]'::jsonb FROM public.courses WHERE slug='digital-onboarding-and-employee-journeys' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.courses (slug,title,summary,category,level,duration_hours,delivery_modes,learning_outcomes,target_roles,status)
VALUES ('hr-data-quality-and-connected-records','HR Data Quality & Connected Records','Make people data usable before adding AI. Practise checking fictional HR records, defining ownership and fixing the causes of poor data.','hr','practitioner',6,ARRAY['in_person','virtual'],'["Create a people-data dictionary", "Complete a data-quality issue register", "Produce a data-quality operating checklist"]'::jsonb,ARRAY['individual_contributor','team_lead'],'published') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,1,'Know your records','Identify core fields, authoritative systems and the purpose of each data item.',2,'["Create a people-data dictionary"]'::jsonb FROM public.courses WHERE slug='hr-data-quality-and-connected-records' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,2,'Find and resolve errors','Use synthetic records to detect duplicates, missing values and conflicting definitions.',2,'["Complete a data-quality issue register"]'::jsonb FROM public.courses WHERE slug='hr-data-quality-and-connected-records' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,3,'Keep records trustworthy','Define validation, access, correction and reconciliation responsibilities.',2,'["Produce a data-quality operating checklist"]'::jsonb FROM public.courses WHERE slug='hr-data-quality-and-connected-records' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.courses (slug,title,summary,category,level,duration_hours,delivery_modes,learning_outcomes,target_roles,status)
VALUES ('ai-assisted-recruitment-operations','AI-Assisted Recruitment Operations','Improve recruitment coordination, role briefs and candidate communications with AI, while keeping selection decisions with accountable people.','hr','practitioner',6,ARRAY['in_person','virtual'],'["Identify an appropriate recruitment support workflow", "Produce a reviewed role brief and message set", "Create a recruitment AI review checklist"]'::jsonb,ARRAY['individual_contributor','team_lead'],'published') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,1,'Redesign recruitment administration','Map scheduling, briefing and communication tasks that can benefit from assistance.',2,'["Identify an appropriate recruitment support workflow"]'::jsonb FROM public.courses WHERE slug='ai-assisted-recruitment-operations' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,2,'Draft with evidence','Check AI-generated role requirements and candidate messages against a fictional approved brief.',2,'["Produce a reviewed role brief and message set"]'::jsonb FROM public.courses WHERE slug='ai-assisted-recruitment-operations' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,3,'Keep decisions accountable','Test unsupported claims and inconsistent wording; define human review and escalation.',2,'["Create a recruitment AI review checklist"]'::jsonb FROM public.courses WHERE slug='ai-assisted-recruitment-operations' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.courses (slug,title,summary,category,level,duration_hours,delivery_modes,learning_outcomes,target_roles,status)
VALUES ('hr-knowledge-and-employee-self-service','HR Knowledge & Employee Self-Service','Prepare a trustworthy HR knowledge base and design an assistant that answers from approved sources and hands sensitive questions to a person.','hr','practitioner',6,ARRAY['in_person','virtual'],'["Create a knowledge inventory", "Produce an answer-and-escalation specification", "Build a self-service evaluation set"]'::jsonb,ARRAY['individual_contributor','team_lead'],'published') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,1,'Make knowledge usable','Organise sample guidance by employee intent, content owner and review date.',2,'["Create a knowledge inventory"]'::jsonb FROM public.courses WHERE slug='hr-knowledge-and-employee-self-service' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,2,'Design helpful answers','Write source-backed answers and define what to do when guidance is absent or conflicting.',2,'["Produce an answer-and-escalation specification"]'::jsonb FROM public.courses WHERE slug='hr-knowledge-and-employee-self-service' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,3,'Test before launch','Challenge the assistant with ambiguous questions, stale sources and requests for private information.',2,'["Build a self-service evaluation set"]'::jsonb FROM public.courses WHERE slug='hr-knowledge-and-employee-self-service' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.courses (slug,title,summary,category,level,duration_hours,delivery_modes,learning_outcomes,target_roles,status)
VALUES ('people-analytics-for-hr-decisions','People Analytics for Better HR Decisions','Turn a people question into a defensible analysis using synthetic data, consistent metrics and a clear explanation of uncertainty.','hr','manager',6,ARRAY['in_person','virtual'],'["Write a people-analytics question brief", "Prepare a metric definition and evidence table", "Produce a decision-ready people insight brief"]'::jsonb,ARRAY['manager','team_lead'],'published') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,1,'Start with the decision','Translate an HR business question into measures, definitions and an appropriate comparison.',2,'["Write a people-analytics question brief"]'::jsonb FROM public.courses WHERE slug='people-analytics-for-hr-decisions' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,2,'Read the evidence','Explore fictional workforce patterns, missing data and the difference between association and cause.',2,'["Prepare a metric definition and evidence table"]'::jsonb FROM public.courses WHERE slug='people-analytics-for-hr-decisions' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,3,'Communicate responsibly','Explain limitations, avoid identifying small groups and propose a testable next step.',2,'["Produce a decision-ready people insight brief"]'::jsonb FROM public.courses WHERE slug='people-analytics-for-hr-decisions' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.courses (slug,title,summary,category,level,duration_hours,delivery_modes,learning_outcomes,target_roles,status)
VALUES ('employee-listening-with-ai','Employee Listening with AI','Use AI to organise fictional employee feedback into useful themes without losing nuance or presenting generated interpretations as facts.','hr','manager',6,ARRAY['in_person','virtual'],'["Create an employee-listening brief", "Produce a verified theme map", "Build a listening-to-action plan"]'::jsonb,ARRAY['manager','team_lead'],'published') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,1,'Design the listening approach','Choose questions, participation measures and appropriate boundaries for feedback use.',2,'["Create an employee-listening brief"]'::jsonb FROM public.courses WHERE slug='employee-listening-with-ai' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,2,'Check AI-generated themes','Compare summaries with synthetic comments and look for omitted or overgeneralised viewpoints.',2,'["Produce a verified theme map"]'::jsonb FROM public.courses WHERE slug='employee-listening-with-ai' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,3,'Close the loop','Prioritise improvements, assign owners and explain how progress will be shared.',2,'["Build a listening-to-action plan"]'::jsonb FROM public.courses WHERE slug='employee-listening-with-ai' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.courses (slug,title,summary,category,level,duration_hours,delivery_modes,learning_outcomes,target_roles,status)
VALUES ('hris-selection-and-integration','HRIS Selection & Connected People Systems','Define what your HR systems must do, evaluate them through practical scenarios and plan reliable data handovers between services.','hr','manager',6,ARRAY['in_person','virtual'],'["Create a prioritised HRIS requirements brief", "Produce an evidence-based evaluation scorecard", "Draft an integration acceptance checklist"]'::jsonb,ARRAY['manager','team_lead'],'published') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,1,'Define the operating needs','Translate employee journeys into requirements and separate essential capabilities from preferences.',2,'["Create a prioritised HRIS requirements brief"]'::jsonb FROM public.courses WHERE slug='hris-selection-and-integration' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,2,'Evaluate through scenarios','Build a vendor demonstration scorecard using realistic onboarding, reporting and access scenarios.',2,'["Produce an evidence-based evaluation scorecard"]'::jsonb FROM public.courses WHERE slug='hris-selection-and-integration' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,3,'Connect systems safely','Map field ownership, failure recovery and reconciliation between a fictional HRIS and adjacent tools.',2,'["Draft an integration acceptance checklist"]'::jsonb FROM public.courses WHERE slug='hris-selection-and-integration' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.courses (slug,title,summary,category,level,duration_hours,delivery_modes,learning_outcomes,target_roles,status)
VALUES ('skills-mapping-and-workforce-planning','Skills Mapping & Technology-Enabled Workforce Planning','Build a practical view of skills and future work, using AI to support exploration while keeping skill claims grounded in evidence.','hr','manager',6,ARRAY['in_person','virtual'],'["Create a task-to-skill map", "Produce an evidence-labelled skills gap map", "Build a workforce development action plan"]'::jsonb,ARRAY['manager','team_lead'],'published') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,1,'Describe the work','Break a business scenario into tasks, capabilities and observable evidence.',2,'["Create a task-to-skill map"]'::jsonb FROM public.courses WHERE slug='skills-mapping-and-workforce-planning' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,2,'Assess the gaps','Review fictional skills records and distinguish verified evidence from self-reported or inferred skills.',2,'["Produce an evidence-labelled skills gap map"]'::jsonb FROM public.courses WHERE slug='skills-mapping-and-workforce-planning' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,3,'Plan the response','Compare development, redeployment and recruitment scenarios with explicit assumptions.',2,'["Build a workforce development action plan"]'::jsonb FROM public.courses WHERE slug='skills-mapping-and-workforce-planning' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.courses (slug,title,summary,category,level,duration_hours,delivery_modes,learning_outcomes,target_roles,status)
VALUES ('learning-operations-and-ai-enabled-development','Learning Operations & AI-Enabled Development','Connect learning needs, course design, delivery and evidence so development programmes support a measurable change in work.','hr','manager',6,ARRAY['in_person','virtual'],'["Create a performance-to-learning brief", "Build a blended learning journey", "Produce a learning operations measurement plan"]'::jsonb,ARRAY['manager','team_lead'],'published') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,1,'Define the performance need','Turn a fictional team challenge into observable learning outcomes and a baseline.',2,'["Create a performance-to-learning brief"]'::jsonb FROM public.courses WHERE slug='learning-operations-and-ai-enabled-development' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,2,'Design the learning journey','Combine AI-assisted drafts, practice, live support and human-reviewed assessment.',2,'["Build a blended learning journey"]'::jsonb FROM public.courses WHERE slug='learning-operations-and-ai-enabled-development' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,3,'Connect the records','Specify completion evidence, reviewer responsibilities and follow-up measures.',2,'["Produce a learning operations measurement plan"]'::jsonb FROM public.courses WHERE slug='learning-operations-and-ai-enabled-development' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.courses (slug,title,summary,category,level,duration_hours,delivery_modes,learning_outcomes,target_roles,status)
VALUES ('redesigning-hr-services-with-agents','Redesigning HR Services with AI Agents','Design a bounded HR agent that can progress work, use approved records and return reviewable outputs, with clear permissions and recovery steps.','hr','manager',6,ARRAY['in_person','virtual'],'["Write an HR agent service brief", "Create an agent control map", "Produce an agent pilot evaluation plan"]'::jsonb,ARRAY['manager','team_lead'],'published') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,1,'Define the service contract','Choose a fictional people-service workflow and specify the agent goal, inputs and allowed actions.',2,'["Write an HR agent service brief"]'::jsonb FROM public.courses WHERE slug='redesigning-hr-services-with-agents' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,2,'Design control and recovery','Set approval points, permission boundaries, duplicate protection and a human handover.',2,'["Create an agent control map"]'::jsonb FROM public.courses WHERE slug='redesigning-hr-services-with-agents' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,3,'Evaluate service reliability','Test success, refusal, incomplete data and interrupted runs against observable acceptance criteria.',2,'["Produce an agent pilot evaluation plan"]'::jsonb FROM public.courses WHERE slug='redesigning-hr-services-with-agents' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.courses (slug,title,summary,category,level,duration_hours,delivery_modes,learning_outcomes,target_roles,status)
VALUES ('hr-transformation-strategy-and-roadmap','HR Transformation Strategy & Roadmap','Shape a practical HR transformation roadmap around employee experience, operating capability and measurable value rather than a list of tools.','hr','leadership',6,ARRAY['in_person','virtual'],'["Write a transformation ambition and baseline", "Build a prioritised transformation roadmap", "Produce a 90-day mobilisation plan"]'::jsonb,ARRAY['director','executive'],'published') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,1,'Set the ambition','Connect business priorities to the current employee experience and HR operating constraints.',2,'["Write a transformation ambition and baseline"]'::jsonb FROM public.courses WHERE slug='hr-transformation-strategy-and-roadmap' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,2,'Sequence the change','Identify dependencies across data, services, technology and people capability.',2,'["Build a prioritised transformation roadmap"]'::jsonb FROM public.courses WHERE slug='hr-transformation-strategy-and-roadmap' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,3,'Make delivery accountable','Define milestone evidence, decision ownership and a benefits review cadence.',2,'["Produce a 90-day mobilisation plan"]'::jsonb FROM public.courses WHERE slug='hr-transformation-strategy-and-roadmap' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.courses (slug,title,summary,category,level,duration_hours,delivery_modes,learning_outcomes,target_roles,status)
VALUES ('responsible-ai-governance-for-hr','Responsible AI Governance for HR Leaders','Establish practical oversight of HR AI use: ownership, evidence, access boundaries and review of consequential decisions by qualified people.','hr','leadership',6,ARRAY['in_person','virtual'],'["Create an HR AI use-case inventory", "Build an HR AI oversight matrix", "Produce a governance operating checklist"]'::jsonb,ARRAY['director','executive'],'published') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,1,'Map uses and consequences','Classify fictional HR AI proposals by purpose, information involved and potential employee impact.',2,'["Create an HR AI use-case inventory"]'::jsonb FROM public.courses WHERE slug='responsible-ai-governance-for-hr' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,2,'Define review and oversight','Specify who approves a pilot, what evidence is required and when specialist advice is needed.',2,'["Build an HR AI oversight matrix"]'::jsonb FROM public.courses WHERE slug='responsible-ai-governance-for-hr' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,3,'Monitor and respond','Plan quality monitoring, employee feedback, incident handling and stop conditions.',2,'["Produce a governance operating checklist"]'::jsonb FROM public.courses WHERE slug='responsible-ai-governance-for-hr' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.courses (slug,title,summary,category,level,duration_hours,delivery_modes,learning_outcomes,target_roles,status)
VALUES ('leading-people-change-in-an-ai-workplace','Leading People Change in an AI Workplace','Lead the people side of AI adoption with clear communication, participation and support as tasks, skills and working practices change.','hr','leadership',6,ARRAY['in_person','virtual'],'["Create a stakeholder and change-impact map", "Produce a participation and communication plan", "Build an adoption and adjustment scorecard"]'::jsonb,ARRAY['director','executive'],'published') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,1,'Understand the change','Map the impact of a fictional technology rollout on tasks, confidence and manager responsibilities.',2,'["Create a stakeholder and change-impact map"]'::jsonb FROM public.courses WHERE slug='leading-people-change-in-an-ai-workplace' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,2,'Build participation','Design employee involvement, manager conversations and realistic capability support.',2,'["Produce a participation and communication plan"]'::jsonb FROM public.courses WHERE slug='leading-people-change-in-an-ai-workplace' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,3,'Measure meaningful adoption','Separate tool activity from better work and create feedback-driven checkpoints.',2,'["Build an adoption and adjustment scorecard"]'::jsonb FROM public.courses WHERE slug='leading-people-change-in-an-ai-workplace' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.courses (slug,title,summary,category,level,duration_hours,delivery_modes,learning_outcomes,target_roles,status)
VALUES ('hr-technology-investment-and-value','HR Technology Investment & Value','Challenge an HR technology business case using realistic costs, operational dependencies and evidence that employee services are improving.','hr','leadership',6,ARRAY['in_person','virtual'],'["Create an investment options brief", "Produce a transparent assumptions register", "Build a benefits and decision-gate plan"]'::jsonb,ARRAY['director','executive'],'published') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,1,'Frame the investment','Define the problem, alternatives and baseline before choosing a product.',2,'["Create an investment options brief"]'::jsonb FROM public.courses WHERE slug='hr-technology-investment-and-value' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,2,'Test the value case','Estimate scenario costs, capacity effects and implementation dependencies without counting benefits twice.',2,'["Produce a transparent assumptions register"]'::jsonb FROM public.courses WHERE slug='hr-technology-investment-and-value' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
INSERT INTO public.course_modules (course_id,position,title,summary,duration_hours,outcomes)
SELECT id,3,'Decide and review','Set pilot criteria, ownership and decision gates for continuing, changing or stopping investment.',2,'["Build a benefits and decision-gate plan"]'::jsonb FROM public.courses WHERE slug='hr-technology-investment-and-value' AND category='hr' ON CONFLICT (course_id,position) DO NOTHING;
