import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight, ArrowRight, Check } from "lucide-react";
import { SiteNav } from "@/components/site-nav";
import { PublicSiteFooter } from "@/components/public/site-footer";
import { getPublicSiteUrl } from "@/lib/site";
import { withSiteShareImages } from "@/lib/social-image";
import { aiLabsGuides } from "@/lib/insights/articles/ai-labs-guides";
import { caseStudies } from "@/lib/case-studies";
import "./labs.css";

const title = "AI Labs | AI Implementation, Robotics & HR Transformation | Experrt";
const description = "Experrt AI Labs builds and implements AI systems, digital products, robotics solutions and HR transformation for SMBs and enterprises. From discovery to delivery.";
export const metadata: Metadata = withSiteShareImages({ title: { absolute: title }, description, alternates: { canonical: "/ai-labs" }, openGraph: { title, description, url: "/ai-labs", type: "website" } });
const services = [
  { id: "ai-systems", number: "01", title: "AI systems that do useful work.", label: "AI & automation", colour: "violet", description: "Turn a working process into a dependable AI-assisted service. We design the workflow, build the integrations and define where people stay in control.", examples: ["Internal knowledge assistants", "Document and case workflows", "Agents connected to business systems"], output: "Working software, integrations, evaluation evidence and an operating runbook." },
  { id: "digital-products", number: "02", title: "From a product idea to something people use.", label: "Technology products", colour: "mint", description: "Build customer portals, internal tools and AI-enabled products around the job your users need to finish. Start with the service journey, then engineer the experience.", examples: ["Customer and partner portals", "Internal operations platforms", "MVPs and existing-product improvements"], output: "A tested product increment, technical documentation and a clear release plan." },
  { id: "robotics", number: "03", title: "Connect the physical and digital.", label: "Robotics implementation", colour: "orange", description: "Explore where robotics fits your operation, then bring process, integration and rollout planning together with the appropriate robotics and safety specialists.", examples: ["Process and site feasibility", "Integration requirements and partner coordination", "Pilot acceptance and operational handover"], output: "A scoped implementation plan, specialist responsibilities and acceptance criteria." },
  { id: "hr-transformation", number: "04", title: "Better people operations. By design.", label: "HR transformation", colour: "blue", description: "Rework the employee and manager experience across HR systems, service workflows and people data. Make the technology serve the people doing the work.", examples: ["Onboarding and employee service journeys", "HR workflow and systems integration", "People reporting and decision support"], output: "A redesigned service, connected workflows and accountable ownership." },
];
const stages = [["Discover", "Understand the work, people, systems and constraints. Agree the problem before choosing a solution."],["Design", "Map the experience and architecture. Define scope, permissions, success measures and the delivery plan."],["Build & validate", "Deliver in reviewable increments. Test with representative cases and the people who will use it."],["Implement & improve", "Roll out with owners, documentation and support arrangements. Review evidence and prioritise the next release."]];
export default function AILabsPage() {
  const base = getPublicSiteUrl();
  const structured = { "@context": "https://schema.org", "@type": "Service", name: "Experrt AI Labs", serviceType: "AI consulting and implementation", description, url: `${base}/ai-labs`, provider: { "@type": "Organization", name: "Experrt", url: base }, hasOfferCatalog: { "@type": "OfferCatalog", name: "Consulting and delivery services", itemListElement: services.map(s => ({ "@type": "Offer", itemOffered: { "@type": "Service", name: s.label, description: s.description } })) } };
  return <div className="labs-page"><SiteNav /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structured).replace(/</g, "\\u003c") }} />
    <main id="main-content">
      <section className="labs-hero labs-wrap">
        <div><p className="labs-kicker">EXPERRT AI LABS / CONSULTING + DELIVERY</p><h1>Build what’s next.<br /><span>Make it work.</span></h1><p className="labs-lead">AI systems. Technology products. Robotics. HR transformation. We help ambitious organisations turn possibilities into working services.</p><div className="labs-actions"><Link className="labs-button" href="/contact?from=ai-labs">Tell us what you want to build <ArrowUpRight size={20}/></Link><a className="labs-text-link" href="#what-we-build">Explore the work <ArrowRight size={18}/></a></div><p className="labs-footnote">Hands-on consulting and implementation for SMBs and enterprises.</p></div>
        <div className="labs-art" aria-label="Illustration of a delivery journey from idea to working system"><div className="labs-orbit" aria-hidden="true"/><span className="labs-art-label">THE SPACE BETWEEN<br/>WHAT IF & WHAT’S NEXT.</span><div className="labs-work-card"><span className="labs-dot"/> A better way of working <strong>Idea → System → Impact</strong><div className="labs-signal"><i/><i/><i/><i/><i/><i/><i/></div><small>Designed. Built. Connected.</small></div><span className="labs-art-note">Human ambition.<br/>Applied intelligence.</span></div>
      </section>
      <section className="labs-proof"><div className="labs-wrap"><p>Already doing the work.</p><h2>Built on hands-on delivery<br/>with SMBs and enterprises.</h2><p>Our consulting and implementation work sits alongside the Experrt learning platform and academy. AI Labs is where we help design, build and put systems into operation. Training can support adoption as a separately scoped part of the work.</p></div></section>
      <section id="what-we-build" className="labs-wrap labs-section"><p className="labs-kicker">FOUR WAYS TO MOVE FORWARD</p><h2>What could we build together?</h2><div className="labs-services">{services.map(s=><article id={s.id} key={s.id} className={`labs-service ${s.colour}`}><div className="labs-service-top"><span>{s.label}</span><span>{s.number}</span></div><h3>{s.title}</h3><p>{s.description}</p><ul>{s.examples.map(e=><li key={e}><Check size={17}/>{e}</li>)}</ul><div className="labs-deliverable"><strong>What you take forward</strong><p>{s.output}</p><Link className="labs-text-link" href={`/contact?from=ai-labs&service=${encodeURIComponent(({"ai-systems":"AI systems & automation","digital-products":"Technology products","robotics":"Robotics implementation","hr-transformation":"HR transformation"} as Record<string,string>)[s.id])}`}>Discuss this project →</Link></div></article>)}</div></section>
      <section className="labs-wrap labs-section"><p className="labs-kicker">INSIDE OUR OWN BUILD</p><h2>See how we put it into practice.</h2><p>Three implementation stories from the Experrt platform, our in-house product.</p><div className="labs-guides">{caseStudies.map(item=><Link key={item.slug} href={`/case-studies/${item.slug}`}><span>{item.category}</span><h3>{item.title}</h3><p>{item.summary}</p><strong>Find out more →</strong></Link>)}</div><p><Link className="labs-text-link" href="/case-studies">Explore our build case studies →</Link></p></section>
      <section className="labs-process"><div className="labs-wrap labs-section"><p className="labs-kicker">FROM THE FIRST QUESTION TO THE NEXT RELEASE</p><h2>A delivery journey.<br/>With a clear next step.</h2><div className="labs-stages">{stages.map(([name,detail],i)=><article key={name}><span>0{i+1}</span><h3>{name}</h3><p>{detail}</p></article>)}</div><p className="labs-process-note">Every engagement has an agreed scope, named owners and acceptance criteria. Timelines, specialist involvement and ongoing support are defined around your project.</p></div></section>
      <section className="labs-wrap labs-section labs-engage"><div><p className="labs-kicker">START WHERE YOU ARE</p><h2>One workflow.<br/>A new product.<br/>A bigger transformation.</h2></div><div><h3>Find the right starting point.</h3><p>Bring an idea, an operational bottleneck or an existing programme that needs delivery support. We’ll work through what is worth building, what needs to connect and what a useful first phase looks like.</p><ul><li><strong>Discovery & roadmap:</strong> a defined problem, priorities and delivery brief.</li><li><strong>Build & implementation:</strong> a scoped project with review points and handover.</li><li><strong>Ongoing improvement:</strong> an agreed programme of iteration and operational support.</li></ul><Link className="labs-button" href="/contact?from=ai-labs">Discuss your project <ArrowUpRight size={20}/></Link></div></section>
      <section className="labs-wrap labs-section"><div className="labs-guide-heading"><div><p className="labs-kicker">THINKING BEFORE BUILDING</p><h2>Practical delivery guides.</h2></div><Link href="/insights/topic/ai-implementation">All implementation insights <ArrowRight size={18}/></Link></div><div className="labs-guides">{[...aiLabsGuides].reverse().map((a,i)=><Link href={`/insights/${a.slug}`} key={a.slug}><span>FIELD GUIDE / 0{i+1}</span><h3>{a.title}</h3><p>{a.description}</p><ArrowUpRight size={22}/></Link>)}</div></section>
      <section className="labs-wrap labs-final"><p className="labs-kicker">LET’S PUT POSSIBILITY TO WORK</p><h2>What needs to work<br/><em>better in your business?</em></h2><Link className="labs-button" href="/contact?from=ai-labs">Let’s build the next chapter <ArrowUpRight size={20}/></Link><p>Looking for courses or workforce learning? <Link href="/courses">Explore the academy.</Link></p></section>
    </main><PublicSiteFooter showDisclaimer={false}/></div>;
}
