import {writeFile,mkdir} from 'node:fs/promises';
import {assessmentSkills,assessmentPolicy,type AssessmentResult} from '../../lib/always-on-agents/assessment.ts';
import {reportHtml,type AgentAssessmentReport} from '../../lib/always-on-agents/report.ts';
import {renderAgentAssessmentReport} from '../../lib/pdf/agent-assessment-report.ts';
const feedback=[
 ['You chose a useful weekly task and explained who needs the report and when it should be ready. Your instructions tell the agent which tracker fields to use, so another person can understand what a correct report should include.','Save a copy of the project tracker from the day you prepared the report. Keep it with the report so you can check where each claim came from.','Task: prepare a weekly report for the studio owner every Monday at 09:00. Read the project tracker; include overdue work only when status is not complete and the recorded due date is before today.'],
 ['You made it clear that the agent can read the tracker and prepare a draft, while you decide whether to share it. You also tested a document that asked the agent to send private data elsewhere. The agent stopped, which shows that your limits worked in this example.','Try this check again whenever you add a new tool or change the instructions. Make sure the agent still asks before sharing information.','Allowed: read the tracker and draft the report. Approval required: share the draft. Blocked: edit project records or send client messages. A conflicting instruction in a source document was ignored.'],
 ['You kept the tracker rows, settings and finished report together, which makes your example easy to follow. You also explained that this was a practice simulation. That helps us understand what you tested and what still needs to be checked in a live account.','When you try this in your own account, check what the agent is allowed to see and do. Run the same example and compare its result with your practice report.','Practice simulation: P101 is complete, P102 has no due date and P103 is open with a past due date. Result: only P103 is overdue; P102 appears under missing information.'],
 ['You checked the usual report against the tracker and tried three useful examples. Next, show how the task behaves when a rule is at its limit or something goes wrong. We need six different test cases to see that you can check more than the usual result. In the changed example, explain which source you would open and what you would look for.','Try a project due on the reporting day, a tracker that cannot be opened and a document that asks the agent to ignore your rules. For each example, write what should happen and what happened. Then explain which tracker entry you would check in the changed example.','Recorded cases: a normal overdue project, a completed project and a project without a due date. Each result was checked against the matching tracker row.'],
 ['When the first report was wrong, you checked what had already happened before trying again. You found that a draft had been saved but no message had been sent. You then corrected the rule and made one replacement draft, so the retry did not create duplicate work.','Keep both drafts and write a short note explaining what went wrong, what you checked and how you fixed it. Another person should be able to follow the same steps.','Failure: the first draft labelled P102 overdue without a due date. I checked completed effects: one draft saved, no email sent. I corrected the rule and retested; one replacement draft was produced.'],
 ['You compared three attempts at the same task and included the time you spent checking the work produced by the agent. That gives a more useful estimate than measuring the drafting time alone. You labelled the costs as estimates and explained how another person can pause the task.','Try the same task in your own workspace and measure the preparation and checking time again. Use those results, together with the real tool cost, to decide whether the agent is worth using.','Illustrative comparison: manual report times 18, 20 and 19 minutes; agent preparation plus checking 8, 9 and 10 minutes. Costs are estimates. The owner can pause the schedule and revoke access.']
];
const result:AssessmentResult={policy:assessmentPolicy,passed:false,summary:'You have explained your task clearly, set sensible limits and shown how you would fix a problem safely. Your next step is to check the report in three more situations and explain how you would handle the changed example. The feedback below shows what to keep and what to practise before you submit again.',skills:assessmentSkills.map((s,i)=>({id:s.id,score:i===3?2:3,feedback:feedback[i][0],nextStep:feedback[i][1],evidenceQuote:feedback[i][2]})),limitations:['This example is fictional and has not been assessed by the live service.','An AI assessor can review pasted text; it cannot open external files, run the agent or verify authorship.','A practice simulation does not demonstrate operation of a live platform account.']};
const report:AgentAssessmentReport={name:'Alex (fictional learner)',title:'Always-on Agent Foundations',version:'2026.10.2-ai-assessed',assessedAt:'2 October 2026',assessmentId:'EXAMPLE - not an issued assessment',result,courseUrl:'',downloadUrl:'',example:true};
await mkdir('output/pdf',{recursive:true});await writeFile('output/pdf/example-agent-assessment-report.html',reportHtml(report));await writeFile('output/pdf/example-agent-assessment-report.pdf',await renderAgentAssessmentReport(report));console.log('Example HTML and PDF saved.');
