import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { getActor } from "@/lib/cohorts";
import { renderEvidencePackPdf } from "@/lib/pdf/evidence-pack-document";
import type { EvidencePackPayload } from "@/lib/evidence-pack";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

/**
 * Render a stored pack to PDF.
 *
 * Rendering reads only `payload`, so the same pack always produces the same
 * document however long after the fact it is downloaded. Row-level security
 * decides who may fetch it.
 */
export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  const actor = await getActor();
  if (!actor) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const supabase = await createClient();
  const { data: pack } = await supabase
    .from("evidence_packs")
    .select("id, period_start, period_end, payload")
    .eq("id", id)
    .maybeSingle();

  if (!pack) return NextResponse.json({ error: "Not found" }, { status: 404 });

  const payload = pack.payload as unknown as EvidencePackPayload;

  if (!payload || payload.version !== 1) {
    return NextResponse.json(
      { error: "This pack was generated by an incompatible version" },
      { status: 409 }
    );
  }

  const buffer = await renderEvidencePackPdf(payload);

  const slug = payload.organisation.name.replace(/[^a-z0-9]+/gi, "-").toLowerCase();
  const filename = `ai-literacy-measures-${slug}-${pack.period_start}-to-${pack.period_end}.pdf`;

  return new NextResponse(new Uint8Array(buffer), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Cache-Control": "no-store",
    },
  });
}
